package com.firstrain.frapi.events;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNull;

import com.firstrain.frapi.events.EventConfigUtil.DelayedConfObj;
import com.firstrain.frapi.events.EventConfigUtil.Filings8KConfObj;
import com.firstrain.frapi.events.EventConfigUtil.WebVolumeConfObj;
import org.junit.Rule;
import org.junit.Test;
import org.junit.rules.ExpectedException;
import org.junit.rules.Timeout;

public class EventConfigUtilDiffblueTest {

  @Rule public final ExpectedException thrown = ExpectedException.none();
  @Rule public final Timeout globalTimeout = new Timeout(10_000);

  /* testedClasses: EventConfigUtil */
  // Test generated by Diffblue Deeptest.

  @Test
  public void getCikCodeOutputZero() {

    // Arrange
    final DelayedConfObj objectUnderTest = new DelayedConfObj();

    // Act
    final long retval = objectUnderTest.getCikCode();

    // Assert
    assertEquals(0L, retval);
  }

  // Test generated by Diffblue Deeptest.

  @Test
  public void getCikCodeOutputZero2() {

    // Arrange
    final Filings8KConfObj objectUnderTest = new Filings8KConfObj();

    // Act
    final long retval = objectUnderTest.getCikCode();

    // Assert
    assertEquals(0L, retval);
  }

  // Test generated by Diffblue Deeptest.

  @Test
  public void getNumDocsEvaluatedOutputZero() {

    // Arrange
    final WebVolumeConfObj objectUnderTest = new WebVolumeConfObj();

    // Act
    final int retval = objectUnderTest.getNumDocsEvaluated();

    // Assert
    assertEquals(0, retval);
  }

  // Test generated by Diffblue Deeptest.

  @Test
  public void getNumDocsTaggedOutputZero() {

    // Arrange
    final WebVolumeConfObj objectUnderTest = new WebVolumeConfObj();

    // Act
    final int retval = objectUnderTest.getNumDocsTagged();

    // Assert
    assertEquals(0, retval);
  }

  // Test generated by Diffblue Deeptest.

  @Test
  public void getTitleOutputNull() {

    // Arrange
    final DelayedConfObj objectUnderTest = new DelayedConfObj();

    // Act
    final String retval = objectUnderTest.getTitle();

    // Assert
    assertNull(retval);
  }

  // Test generated by Diffblue Deeptest.

  @Test
  public void getTitleOutputNull2() {

    // Arrange
    final Filings8KConfObj objectUnderTest = new Filings8KConfObj();

    // Act
    final String retval = objectUnderTest.getTitle();

    // Assert
    assertNull(retval);
  }

  // Test generated by Diffblue Deeptest.

  @Test
  public void getTitleOutputNull3() {

    // Arrange
    final WebVolumeConfObj objectUnderTest = new WebVolumeConfObj();

    // Act
    final String retval = objectUnderTest.getTitle();

    // Assert
    assertNull(retval);
  }

  // Test generated by Diffblue Deeptest.

  @Test
  public void getTitleSearchUrlOutputNull() {

    // Arrange
    final WebVolumeConfObj objectUnderTest = new WebVolumeConfObj();

    // Act
    final String retval = objectUnderTest.getTitleSearchUrl();

    // Assert
    assertNull(retval);
  }

  // Test generated by Diffblue Deeptest.

  @Test
  public void getTitleUrlOutputNull() {

    // Arrange
    final DelayedConfObj objectUnderTest = new DelayedConfObj();

    // Act
    final String retval = objectUnderTest.getTitleUrl();

    // Assert
    assertNull(retval);
  }

  // Test generated by Diffblue Deeptest.

  @Test
  public void getTitleUrlOutputNull2() {

    // Arrange
    final Filings8KConfObj objectUnderTest = new Filings8KConfObj();

    // Act
    final String retval = objectUnderTest.getTitleUrl();

    // Assert
    assertNull(retval);
  }

  // Test generated by Diffblue Deeptest.

  @Test
  public void getTitleUrlOutputNull3() {

    // Arrange
    final WebVolumeConfObj objectUnderTest = new WebVolumeConfObj();

    // Act
    final String retval = objectUnderTest.getTitleUrl();

    // Assert
    assertNull(retval);
  }
}
