package com.firstrain.frapi.events;

import static org.junit.Assert.assertArrayEquals;
import static org.junit.Assert.assertEquals;

import com.firstrain.frapi.events.IEvents.EventDisplayType;
import com.firstrain.frapi.events.IEvents.EventEntityTypeEnum;
import com.firstrain.frapi.events.IEvents.EventGroupEnum;
import org.junit.Rule;
import org.junit.Test;
import org.junit.rules.ExpectedException;
import org.junit.rules.Timeout;

public class IEvents_1DiffblueTest {

  @Rule public final ExpectedException thrown = ExpectedException.none();
  @Rule public final Timeout globalTimeout = new Timeout(10_000);

  /* testedClasses: IEvents_1 */
  // Test generated by Diffblue Deeptest.

  @Test
  public void getIdOutputPositive() {

    // Arrange
    final EventEntityTypeEnum objectUnderTest = EventEntityTypeEnum.TYPE_COMPANY;

    // Act
    final int retval = objectUnderTest.getId();

    // Assert
    assertEquals(1, retval);
  }

  // Test generated by Diffblue Deeptest.

  @Test
  public void getIdOutputPositive2() {

    // Arrange
    final EventGroupEnum objectUnderTest = EventGroupEnum.GROUP_SHARE_BUYBACK;

    // Act
    final int retval = objectUnderTest.getId();

    // Assert
    assertEquals(11, retval);
  }

  // Test generated by Diffblue Deeptest.

  @Test
  public void getLabelOutputNotNull() {

    // Arrange
    final EventEntityTypeEnum objectUnderTest = EventEntityTypeEnum.TYPE_COMPANY;

    // Act
    final String retval = objectUnderTest.getLabel();

    // Assert
    assertEquals("Company", retval);
  }

  // Test generated by Diffblue Deeptest.

  @Test
  public void getLabelOutputNotNull2() {

    // Arrange
    final EventGroupEnum objectUnderTest = EventGroupEnum.GROUP_SHARE_BUYBACK;

    // Act
    final String retval = objectUnderTest.getLabel();

    // Assert
    assertEquals("Share Buyback", retval);
  }

  // Test generated by Diffblue Deeptest.

  @Test
  public void valuesOutput2() {

    // Act
    final EventEntityTypeEnum[] retval = EventEntityTypeEnum.values();

    // Assert
    assertArrayEquals(
        new EventEntityTypeEnum[] {
          EventEntityTypeEnum.TYPE_COMPANY, EventEntityTypeEnum.TYPE_TOPIC
        },
        retval);
  }

  // Test generated by Diffblue Deeptest.

  @Test
  public void valuesOutput3() {

    // Act
    final EventDisplayType[] retval = EventDisplayType.values();

    // Assert
    assertArrayEquals(
        new EventDisplayType[] {
          EventDisplayType.PLAIN, EventDisplayType.BOLD, EventDisplayType.BOLD_LARGE
        },
        retval);
  }

  // Test generated by Diffblue Deeptest.

  @Test
  public void valuesOutput12() {

    // Act
    final EventGroupEnum[] retval = EventGroupEnum.values();

    // Assert
    assertArrayEquals(
        new EventGroupEnum[] {
          EventGroupEnum.GROUP_MGMT_CHANGE,
          EventGroupEnum.GROUP_STOCK_PRICE,
          EventGroupEnum.GROUP_WEB_VOLUME,
          EventGroupEnum.GROUP_8K_FILING,
          EventGroupEnum.GROUP_DELAYED_FILING,
          EventGroupEnum.GROUP_MGMT_POSITIVE_NEGATIVE_COMMENTS,
          EventGroupEnum.GROUP_PUBLIC_OFFERING,
          EventGroupEnum.GROUP_PRIVATE_PLACEMENT,
          EventGroupEnum.GROUP_SPINOFF_SPILTOFF,
          EventGroupEnum.GROUP_MERGER_ACQUISITION,
          EventGroupEnum.GROUP_SHARE_BUYBACK,
          EventGroupEnum.GROUP_SHELF_REGISTRATIONS
        },
        retval);
  }
}
