package com.firstrain.frapi.util;

public interface StatusCode {

	/**
	 * Entity can be company,industry,region,topic, bizline,monitor
	 */

	int ENTITY_NOT_FOUND = 100;
	int USER_NOT_FOUND = 101;
	int INVALID_TIMEZONE = 102;
	int ILLEGAL_ARGUMENT = 103;
	int INSUFFICIENT_ARGUMENT = 104;
	int INVALID_CREDENTIAL = 105;
	int INSUFFICIENT_PRIVILEGE = 106;
	int CANNOT_DELETE_ALL_ITEMS = 107;
	int USER_ALREADY_EXISTS = 108;
	int INVALID_AUTHKEY = 109;
	int USER_DOESNOT_OWN_MONITOR = 110;
	int NO_ITEMS = 111;
	int GROUP_ALREADY_EXIST = 112;
	int GROUP_CREATION_LIMIT_EXCEEDS = 113;
	int INACTIVE_USER_STATUS = 114;
	int FILTERS_NOT_FOUND = 115;
	int EXPIRED_AUTHKEY = 116;
	int FILTERS_ALREADY_PRESENT = 117;
	int ENTITIES_NOT_FOUND = 118;
	int ENTITY_ALREADY_EXISTS = 119;
	int MONITOR_ALREADY_EXISTS = 120;
	int NO_MONITORS = 121;
	int EMAIL_ALREADY_EXISTS = 122;
	int ARTICLE_ALREADY_HIDDEN = 123;
	int ITEM_DOES_NOT_EXIST = 124;
	int ANONYMOUS_USER_NOT_FOUND = 125;
	int ARTICLE_UNDER_PROCESSING = 126;
	int ARTICLE_TAKED_DOWN = 127;
	int INVALID_SECTION = 128;
	int MONITOR_SEARCH_LIMIT_EXCEEDED = 129;
	int NO_ITEMS_IN_MONITOR = 130;
	int NO_EMAIL_SCHEDULE = 131;
	int NO_EMAIL_SENT = 132;
	int PEERS_NOT_FOUND = 133;
	int REQUEST_SUCCESS = 200;
	int PARTIAL_SUCCESS = 206;
	int INTERNAL_SERVER_ERROR = 500;
	int SERVICE_NOT_AVAIL = 503;
	int RSOURCE_NOT_FOUND = 404;

}
