package com.firstrain.web.controller.core;

import static org.junit.Assert.assertArrayEquals;
import static org.junit.Assert.assertEquals;

import com.diffblue.deeptestutils.Reflector;
import java.lang.reflect.Method;
import org.junit.Rule;
import org.junit.Test;
import org.junit.rules.ExpectedException;
import org.junit.rules.Timeout;

public class OperationTypeDiffblueTest {

  @Rule public final ExpectedException thrown = ExpectedException.none();
  @Rule public final Timeout globalTimeout = new Timeout(10_000);

  /* testedClasses: OperationType */
  // Test generated by Diffblue Deeptest.

  @Test
  public void getAttributeOutputNotNull() throws Exception {

    // Arrange
    final OperationType objectUnderTest = OperationType.ADD_FILTER;

    // Act
    final Class<?> classUnderTest =
        Reflector.forName("com.firstrain.web.controller.core.OperationType");
    final Method methodUnderTest = classUnderTest.getDeclaredMethod("getAttribute");
    methodUnderTest.setAccessible(true);
    final String retval = (String) methodUnderTest.invoke(objectUnderTest);

    // Assert
    assertEquals("addfilter", retval);
  }

  // Test generated by Diffblue Deeptest.

  @Test
  public void getRequestParamOutputNotNull() throws Exception {

    // Arrange
    final OperationType objectUnderTest = OperationType.ADD_FILTER;

    // Act
    final Class<?> classUnderTest =
        Reflector.forName("com.firstrain.web.controller.core.OperationType");
    final Method methodUnderTest = classUnderTest.getDeclaredMethod("getRequestParam");
    methodUnderTest.setAccessible(true);
    final String retval = (String) methodUnderTest.invoke(objectUnderTest);

    // Assert
    assertEquals("fq", retval);
  }

  // Test generated by Diffblue Deeptest.

  @Test
  public void valuesOutput4() {

    // Act
    final OperationType[] retval = OperationType.values();

    // Assert
    assertArrayEquals(
        new OperationType[] {
          OperationType.ADD_ENTITY, OperationType.REMOVE_ENTITY,
          OperationType.ADD_FILTER, OperationType.REMOVE_FILTER
        },
        retval);
  }
}
