/*
 * This file was automatically generated by EvoSuite
 * Thu Jun 28 17:12:42 GMT 2018
 */

package com.firstrain.frapi.pojo;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNull;

import org.junit.Test;


public class ItemsESTest {

	@Test(timeout = 4000)
	public void test00() throws Exception {
		Items items0 = new Items();
		items0.setScope(null);
		assertNull(items0.getName());
	}

	@Test(timeout = 4000)
	public void test01() throws Exception {
		Items items0 = new Items();
		items0.setQ("_{y`M5OA6M(JR,i<@aD");
		assertNull(items0.getId());
	}

	@Test(timeout = 4000)
	public void test02() throws Exception {
		Items items0 = new Items();
		items0.setName("}q%cM>F#]I");
		assertNull(items0.getId());
	}

	@Test(timeout = 4000)
	public void test03() throws Exception {
		Items items0 = new Items();
		Long long0 = (-1748L);
		items0.setId(long0);
		assertNull(items0.getScope());
	}

	@Test(timeout = 4000)
	public void test04() throws Exception {
		Items items0 = new Items();
		items0.setFq("");
		assertNull(items0.getData());
	}

	@Test(timeout = 4000)
	public void test05() throws Exception {
		Items items0 = new Items();
		Entity entity0 = new Entity();
		items0.setEntity(entity0);
		assertEquals(0, entity0.getIndustryCatId());
	}

	@Test(timeout = 4000)
	public void test06() throws Exception {
		Items items0 = new Items();
		Integer integer0 = (-2505);
		items0.setDocCount(integer0);
		assertNull(items0.getData());
	}

	@Test(timeout = 4000)
	public void test07() throws Exception {
		Items items0 = new Items();
		items0.setData("TYPE_EIGHT_K_EVENT_ITEM_6_04");
		assertNull(items0.getName());
	}

	@Test(timeout = 4000)
	public void test08() throws Exception {
		Items items0 = new Items();
		Integer integer0 = items0.getScope();
		assertNull(integer0);
	}

	@Test(timeout = 4000)
	public void test09() throws Exception {
		Items items0 = new Items();
		String string0 = items0.getQ();
		assertNull(string0);
	}

	@Test(timeout = 4000)
	public void test10() throws Exception {
		Items items0 = new Items();
		String string0 = items0.getName();
		assertNull(string0);
	}

	@Test(timeout = 4000)
	public void test11() throws Exception {
		Items items0 = new Items();
		Long long0 = items0.getId();
		assertNull(long0);
	}

	@Test(timeout = 4000)
	public void test12() throws Exception {
		Items items0 = new Items();
		String string0 = items0.getFq();
		assertNull(string0);
	}

	@Test(timeout = 4000)
	public void test13() throws Exception {
		Items items0 = new Items();
		Entity entity0 = items0.getEntity();
		assertNull(entity0);
	}

	@Test(timeout = 4000)
	public void test14() throws Exception {
		Items items0 = new Items();
		Integer integer0 = items0.getDocCount();
		assertNull(integer0);
	}

	@Test(timeout = 4000)
	public void test15() throws Exception {
		Items items0 = new Items();
		String string0 = items0.getData();
		assertNull(string0);
	}
}
