/*
 * This file was automatically generated by EvoSuite
 * Mon Jul 02 18:47:26 GMT 2018
 */

package com.firstrain.web.util;

import static org.junit.Assert.assertNull;

import com.firstrain.frapi.pojo.AuthAPIResponse;
import org.junit.Test;


public class AuthAPIResponseThreadLocalESTest {

	@Test(timeout = 4000)
	public void test0() throws Exception {
		AuthAPIResponseThreadLocal.set(null);
	}

	@Test(timeout = 4000)
	public void test1() throws Exception {
		AuthAPIResponseThreadLocal.remove();
	}

	@Test(timeout = 4000)
	public void test2() throws Exception {
		AuthAPIResponse authAPIResponse0 = AuthAPIResponseThreadLocal.get();
		assertNull(authAPIResponse0);
	}

	@Test(timeout = 4000)
	public void test3() throws Exception {
		AuthAPIResponseThreadLocal authAPIResponseThreadLocal0 = new AuthAPIResponseThreadLocal();
	}
}
