/*
 * This file was automatically generated by EvoSuite
 * Mon Jul 02 17:49:47 GMT 2018
 */

package com.firstrain.frapi.repository.impl;

import static org.junit.Assert.assertEquals;

import com.firstrain.db.obj.APIAuthKey;
import org.evosuite.runtime.javaee.injection.Injector;
import org.junit.Test;


public class AuthServiceRepositoryImplESTest {

	@Test(timeout = 4000, expected = NullPointerException.class)
	public void test0() throws Exception {
		APIAuthKey aPIAuthKey0 = new APIAuthKey();
		AuthServiceRepositoryImpl authServiceRepositoryImpl0 = new AuthServiceRepositoryImpl();
		Injector.executePostConstruct(authServiceRepositoryImpl0,
				com.firstrain.frapi.repository.impl.AuthServiceRepositoryImpl.class);
		authServiceRepositoryImpl0.persistAuthKey(aPIAuthKey0);
	}

	@Test(timeout = 4000)
	public void test1() throws Exception {
		String[] stringArray0 = new String[9];
		AuthServiceRepositoryImpl.main(stringArray0);
		assertEquals(9, stringArray0.length);
	}

	@Test(timeout = 4000, expected = NullPointerException.class)
	public void test2() throws Exception {
		AuthServiceRepositoryImpl authServiceRepositoryImpl0 = new AuthServiceRepositoryImpl();
		Injector.executePostConstruct(authServiceRepositoryImpl0,
				com.firstrain.frapi.repository.impl.AuthServiceRepositoryImpl.class);
		authServiceRepositoryImpl0.getAccountById((-61L));
	}

	@Test(timeout = 4000)
	public void test3() throws Exception {
		AuthServiceRepositoryImpl authServiceRepositoryImpl0 = new AuthServiceRepositoryImpl();
		Injector.executePostConstruct(authServiceRepositoryImpl0,
				com.firstrain.frapi.repository.impl.AuthServiceRepositoryImpl.class);
		String string0 = authServiceRepositoryImpl0.generateAuthKey();
		//  // Unstable assertion: assertEquals("9dc7e05db8ad06bfd7963e708919c0efd7f0784d7b8f0fdf2eb4d05d9c995f68", string0);
	}
}
