/*
 * This file was automatically generated by EvoSuite
 * Mon Jul 02 17:41:44 GMT 2018
 */

package com.firstrain.frapi.util;

import static org.evosuite.shaded.org.mockito.Mockito.any;
import static org.evosuite.shaded.org.mockito.Mockito.anyString;
import static org.evosuite.shaded.org.mockito.Mockito.doReturn;
import static org.evosuite.shaded.org.mockito.Mockito.mock;
import static org.junit.Assert.assertEquals;

import java.io.ByteArrayInputStream;
import java.io.FileDescriptor;
import java.io.InputStream;
import java.util.Set;
import javax.xml.parsers.DocumentBuilderFactory;
import javax.xml.xpath.XPath;
import org.dom4j.dom.DOMCDATA;
import org.dom4j.dom.DOMDocument;
import org.dom4j.dom.DOMNodeHelper;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.evosuite.runtime.mock.java.io.MockFileInputStream;
import org.junit.Test;
import org.w3c.dom.Document;
import org.w3c.dom.Node;
import org.w3c.dom.NodeList;
import org.w3c.dom.Text;

public class CompanyEndingLoaderESTest {

	@Test(timeout = 4000, expected = NullPointerException.class)
	public void test0() throws Exception {
		DOMCDATA dOMCDATA0 = new DOMCDATA("h1e2voywc9");
		NodeList nodeList0 = dOMCDATA0.getChildNodes();
		// Undeclared exception!
		CompanyEndingLoader.loadCompanyEnding(null, null, nodeList0, 0);
	}

	@Test(timeout = 4000)
	public void test1() throws Exception {
		CompanyEndingLoader.loadCompanyEnding(null, null, null);
	}

	@Test(timeout = 4000, expected = NullPointerException.class)
	public void test2() throws Exception {
		DOMDocument dOMDocument0 = new DOMDocument((String) null);
		Text text0 = dOMDocument0.createTextNode("$7");
		// Undeclared exception!
		CompanyEndingLoader.loadCompanyEnding(null, null, text0);
	}

	@Test(timeout = 4000, expected = NullPointerException.class)
	public void test3() throws Exception {
		DOMNodeHelper.EmptyNodeList dOMNodeHelper_EmptyNodeList0 = new DOMNodeHelper.EmptyNodeList();
		XPath xPath0 = mock(XPath.class, new ViolatedAssumptionAnswer());
		doReturn(dOMNodeHelper_EmptyNodeList0).when(xPath0)
				.evaluate(anyString(), any(), any(javax.xml.namespace.QName.class));
		// Undeclared exception!
		CompanyEndingLoader
				.loadCompanyEnding(null, null, xPath0, null);
	}

	@Test(timeout = 4000)
	public void test4() throws Exception {
		DocumentBuilderFactory documentBuilderFactory0 = DocumentBuilderFactory.newInstance();
		byte[] byteArray0 = new byte[0];
		ByteArrayInputStream byteArrayInputStream0 = new ByteArrayInputStream(byteArray0);
		CompanyEndingLoader
				.loadCompanyEnding(null, null, documentBuilderFactory0,
						byteArrayInputStream0);
		assertEquals(0, byteArrayInputStream0.available());
	}

	@Test(timeout = 4000)
	public void test5() throws Exception {
		DocumentBuilderFactory documentBuilderFactory0 = DocumentBuilderFactory.newInstance();
		FileDescriptor fileDescriptor0 = new FileDescriptor();
		MockFileInputStream mockFileInputStream0 = new MockFileInputStream(fileDescriptor0);
		CompanyEndingLoader
				.loadCompanyEnding(null, null, documentBuilderFactory0,
						mockFileInputStream0);
	}
}
