package com.firstrain.frapi.util;

import com.diffblue.deeptestutils.Reflector;
import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationTargetException;
import javax.xml.xpath.XPath;
import org.junit.Rule;
import org.junit.Test;
import org.junit.rules.ExpectedException;
import org.junit.rules.Timeout;
import org.w3c.dom.Document;

public class CompanyEndingLoaderDiffblueTest {

  @Rule public final ExpectedException thrown = ExpectedException.none();
  @Rule public final Timeout globalTimeout = new Timeout(10_000);

  /* testedClasses: CompanyEndingLoader */
  // Test generated by Diffblue Deeptest.

  @Test
  public void constructorOutputUnsupportedOperationException() throws Throwable {

    // Act, creating object to test constructor
    thrown.expect(UnsupportedOperationException.class);
    try {
      final Class<?> classUnderTest =
          Reflector.forName("com.firstrain.frapi.util.CompanyEndingLoader");
      final Constructor<?> ctor = classUnderTest.getDeclaredConstructor();
      ctor.setAccessible(true);
      final Object objectUnderTest = ctor.newInstance();
    } catch (InvocationTargetException ex) {
      throw ex.getCause();
    }

    // Method is not expected to return due to exception thrown
  }

  // Test generated by Diffblue Deeptest.

  @Test
  public void loadCompanyEndingInput00NullNullOutputNullPointerException() throws Exception {

    // Arrange
    final java.util.HashSet<String> words = new java.util.HashSet<String>();
    final java.util.HashSet<String> wordsRegex = new java.util.HashSet<String>();
    final XPath xPath = null;
    final Document document = null;

    // Act
    thrown.expect(NullPointerException.class);
    CompanyEndingLoader.loadCompanyEnding(words, wordsRegex, xPath, document);

    // Method is not expected to return due to exception thrown
  }
}
