package com.firstrain.frapi.util;

import static org.junit.Assert.assertEquals;

import com.diffblue.deeptestutils.Reflector;
import org.junit.Rule;
import org.junit.Test;
import org.junit.rules.ExpectedException;
import org.junit.rules.Timeout;

public class DateBucketUtilsDiffblueTest {

  @Rule public final ExpectedException thrown = ExpectedException.none();
  @Rule public final Timeout globalTimeout = new Timeout(10_000);

  /* testedClasses: DateBucketUtils */
  // Test generated by Diffblue Deeptest.

  @Test
  public void constructorOutputVoid() {

    // Act, creating object to test constructor
    final DateBucketUtils objectUnderTest = new DateBucketUtils();
  }

  // Test generated by Diffblue Deeptest.

  @Test
  public void toStringOutputNotNull() throws Exception {

    // Arrange
    final DateBucketUtils.LabelVsDate objectUnderTest =
        (DateBucketUtils.LabelVsDate)
            Reflector.getInstance("com.firstrain.frapi.util.DateBucketUtils$LabelVsDate");
    objectUnderTest.date = null;
    Reflector.setField(objectUnderTest, "this$0", null);
    objectUnderTest.bucketToMerge = null;
    objectUnderTest.label = "!!!!!!";

    // Act
    final String retval = objectUnderTest.toString();

    // Assert
    assertEquals("!!!!!! == null", retval);
  }
}
