/*
 * This file was automatically generated by EvoSuite
 * Mon Jul 02 17:39:00 GMT 2018
 */

package com.firstrain.frapi.util;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertTrue;

import java.util.List;
import org.junit.Test;


public class QueryParser$ParseResultESTest {

	@Test(timeout = 4000)
	public void test0() throws Exception {
		QueryParser.ParseResult queryParser_ParseResult0 = new QueryParser.ParseResult("");
		List<String> list0 = queryParser_ParseResult0.getParams();
		assertTrue(list0.isEmpty());
	}

	@Test(timeout = 4000)
	public void test1() throws Exception {
		QueryParser.ParseResult queryParser_ParseResult0 = new QueryParser.ParseResult("-;");
		List<String> list0 = queryParser_ParseResult0.getParamValues(null);
		assertFalse(list0.contains("-;"));
	}

	@Test(timeout = 4000)
	public void test2() throws Exception {
		QueryParser.ParseResult queryParser_ParseResult0 = new QueryParser.ParseResult("(");
		String string0 = queryParser_ParseResult0.getInput();
		assertEquals("(", string0);
	}

	@Test(timeout = 4000)
	public void test3() throws Exception {
		QueryParser.ParseResult queryParser_ParseResult0 = new QueryParser.ParseResult("-;");
		String string0 = queryParser_ParseResult0.getFirstParamValue("-;");
		assertEquals("", string0);
	}
}
