package com.firstrain.frapi.service.impl;

import static org.junit.Assert.assertEquals;

import com.diffblue.deeptestutils.Reflector;
import java.util.HashSet;
import java.util.Set;
import org.junit.Rule;
import org.junit.Test;
import org.junit.rules.ExpectedException;
import org.junit.rules.Timeout;

public class CompanyEndingWordsDiffblueTest {

  @Rule public final ExpectedException thrown = ExpectedException.none();
  @Rule public final Timeout globalTimeout = new Timeout(10_000);

  /* testedClasses: CompanyEndingWords */
  // Test generated by Diffblue Deeptest.

  @Test
  public void getCompanyEndingWordsOutput0() {

    // Arrange
    final CompanyEndingWords objectUnderTest = new CompanyEndingWords();
    Reflector.setField(objectUnderTest, "st_THE_Regex", null);
    Reflector.setField(objectUnderTest, "companyEndingWordsRegex", null);
    final HashSet hashSet = new HashSet();
    Reflector.setField(objectUnderTest, "companyEndingWords", hashSet);
    Reflector.setField(objectUnderTest, "LOG", null);

    // Act
    final Set<String> retval = objectUnderTest.getCompanyEndingWords();

    // Assert
    final HashSet<String> hashSet1 = new HashSet<String>();
    assertEquals(hashSet1, retval);
  }

  // Test generated by Diffblue Deeptest.

  @Test
  public void getCompanyEndingWordsRegexOutput0() {

    // Arrange
    final CompanyEndingWords objectUnderTest = new CompanyEndingWords();
    Reflector.setField(objectUnderTest, "st_THE_Regex", null);
    final HashSet hashSet = new HashSet();
    Reflector.setField(objectUnderTest, "companyEndingWordsRegex", hashSet);
    Reflector.setField(objectUnderTest, "companyEndingWords", null);
    Reflector.setField(objectUnderTest, "LOG", null);

    // Act
    final Set<String> retval = objectUnderTest.getCompanyEndingWordsRegex();

    // Assert
    final HashSet<String> hashSet1 = new HashSet<String>();
    assertEquals(hashSet1, retval);
  }
}
