/*
 * This file was automatically generated by EvoSuite
 * Mon Jul 02 15:57:27 GMT 2018
 */

package com.firstrain.web.service.core;

import org.evosuite.runtime.javaee.injection.Injector;
import org.junit.Test;

public class FREntityMappingESTest {

	@Test(timeout = 4000, expected = RuntimeException.class)
	public void test0() {
		FREntityMapping fREntityMapping0 = new FREntityMapping();
		LoadConfigurationComponentByExternalUrl loadConfigurationComponentByExternalUrl0 =
				new LoadConfigurationComponentByExternalUrl();
		FRResourceUtils fRResourceUtils0 = new FRResourceUtils();
		Injector.inject(
				loadConfigurationComponentByExternalUrl0,
				com.firstrain.web.service.core.LoadConfigurationComponentByExternalUrl.class,
				"frResourceUtils",
				fRResourceUtils0);
		Injector.validateBean(
				loadConfigurationComponentByExternalUrl0,
				com.firstrain.web.service.core.LoadConfigurationComponentByExternalUrl.class);
		fREntityMapping0.load(null);
		Injector.inject(
				fREntityMapping0,
				com.firstrain.web.service.core.FREntityMapping.class,
				"loadConfigurationComponentByExternalUrl",
				loadConfigurationComponentByExternalUrl0);
		Injector.validateBean(fREntityMapping0,
				com.firstrain.web.service.core.FREntityMapping.class);
		// Undeclared exception!
		Injector.executePostConstruct(fREntityMapping0,
				com.firstrain.web.service.core.FREntityMapping.class);
	}

	@Test(timeout = 4000, expected = RuntimeException.class)
	public void test1() throws Exception {
		FREntityMapping fREntityMapping0 = new FREntityMapping();
		LoadConfigurationComponentByExternalUrl loadConfigurationComponentByExternalUrl0 =
				new LoadConfigurationComponentByExternalUrl();
		FRResourceUtils fRResourceUtils0 = new FRResourceUtils();
		Injector.inject(
				loadConfigurationComponentByExternalUrl0,
				com.firstrain.web.service.core.LoadConfigurationComponentByExternalUrl.class,
				"frResourceUtils",
				fRResourceUtils0);
		Injector.validateBean(
				loadConfigurationComponentByExternalUrl0,
				com.firstrain.web.service.core.LoadConfigurationComponentByExternalUrl.class);
		Injector.inject(
				fREntityMapping0,
				com.firstrain.web.service.core.FREntityMapping.class,
				"loadConfigurationComponentByExternalUrl",
				loadConfigurationComponentByExternalUrl0);
		fREntityMapping0.load();
		Injector.validateBean(fREntityMapping0,
				com.firstrain.web.service.core.FREntityMapping.class);
		// Undeclared exception!
		Injector.executePostConstruct(fREntityMapping0,
				com.firstrain.web.service.core.FREntityMapping.class);
	}

	@Test(timeout = 4000, expected = RuntimeException.class)
	public void test2() {
		FREntityMapping fREntityMapping0 = new FREntityMapping();
		LoadConfigurationComponentByExternalUrl loadConfigurationComponentByExternalUrl0 =
				new LoadConfigurationComponentByExternalUrl();
		FRResourceUtils fRResourceUtils0 = new FRResourceUtils();
		Injector.inject(
				loadConfigurationComponentByExternalUrl0,
				com.firstrain.web.service.core.LoadConfigurationComponentByExternalUrl.class,
				"frResourceUtils",
				fRResourceUtils0);
		Injector.validateBean(
				loadConfigurationComponentByExternalUrl0,
				com.firstrain.web.service.core.LoadConfigurationComponentByExternalUrl.class);
		fREntityMapping0.getCatIdVsFREntity("/K^_OHB$mP");
		Injector.inject(
				fREntityMapping0,
				com.firstrain.web.service.core.FREntityMapping.class,
				"loadConfigurationComponentByExternalUrl",
				loadConfigurationComponentByExternalUrl0);
		Injector.validateBean(fREntityMapping0,
				com.firstrain.web.service.core.FREntityMapping.class);
		// Undeclared exception!
		Injector.executePostConstruct(fREntityMapping0,
				com.firstrain.web.service.core.FREntityMapping.class);
	}
}
