/*
 * This file was automatically generated by EvoSuite
 * Mon Jul 02 16:01:07 GMT 2018
 */

package com.firstrain.web.service.core;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertNull;

import com.firstrain.web.pojo.CreateInputBean;
import com.firstrain.web.response.JSONResponse;
import org.evosuite.runtime.javaee.injection.Injector;
import org.junit.Test;

public class RequestParsingServiceESTest {

	@Test(timeout = 4000, expected = RuntimeException.class)
	public void test00() {
		RequestParsingService requestParsingService0 = new RequestParsingService();
		CreateInputBean createInputBean0 = new CreateInputBean();
		// Undeclared exception!
		requestParsingService0.validateTaxonomyDirectiveForList(createInputBean0);
	}

	@Test(timeout = 4000, expected = NullPointerException.class)
	public void test01() {
		RequestParsingService requestParsingService0 = new RequestParsingService();
		// Undeclared exception!
		requestParsingService0.validateTaxonomyDirective(
				null, "com.fasterxml.jackson.databind.introspect.ClassIntrospector");
	}

	@Test(timeout = 4000, expected = RuntimeException.class)
	public void test02() {
		RequestParsingService requestParsingService0 = new RequestParsingService();
		CreateInputBean createInputBean0 = new CreateInputBean();
		// Undeclared exception!
		requestParsingService0.validateTaxonomyDirective(createInputBean0);
	}

	@Test(timeout = 4000)
	public void test03() {
		RequestParsingService requestParsingService0 = new RequestParsingService();
		requestParsingService0.validateState("inactive");
	}

	@Test(timeout = 4000, expected = RuntimeException.class)
	public void test04() {
		RequestParsingService requestParsingService0 = new RequestParsingService();
		// Undeclared exception!
		requestParsingService0.validateState("");
	}

	@Test(timeout = 4000, expected = NullPointerException.class)
	public void test05() {
		RequestParsingService requestParsingService0 = new RequestParsingService();
		CreateInputBean createInputBean0 = new CreateInputBean();
		// Undeclared exception!
		requestParsingService0.validateSearchTokenFromEntityInfoCache("", false, createInputBean0);
	}

	@Test(timeout = 4000, expected = RuntimeException.class)
	public void test06() throws Exception {
		RequestParsingService requestParsingService0 = new RequestParsingService();
		FREntityMapping fREntityMapping0 = new FREntityMapping();
		LoadConfigurationComponentByExternalUrl loadConfigurationComponentByExternalUrl0 =
				new LoadConfigurationComponentByExternalUrl();
		FRResourceUtils fRResourceUtils0 = new FRResourceUtils();
		Injector.inject(
				loadConfigurationComponentByExternalUrl0,
				com.firstrain.web.service.core.LoadConfigurationComponentByExternalUrl.class,
				"frResourceUtils",
				fRResourceUtils0);
		Injector.validateBean(
				loadConfigurationComponentByExternalUrl0,
				com.firstrain.web.service.core.LoadConfigurationComponentByExternalUrl.class);
		CreateInputBean createInputBean0 = new CreateInputBean();
		requestParsingService0.validatePrivateEntityInputFields(createInputBean0, false);
	}

	@Test(timeout = 4000, expected = RuntimeException.class)
	public void test07() throws Exception {
		RequestParsingService requestParsingService0 = new RequestParsingService();
		CreateInputBean createInputBean0 = new CreateInputBean();
		// Undeclared exception!
		requestParsingService0.validateGetDefinitionInputFields(createInputBean0);
	}

	@Test(timeout = 4000, expected = RuntimeException.class)
	public void test08() throws Exception {
		RequestParsingService requestParsingService0 = new RequestParsingService();
		CreateInputBean createInputBean0 = new CreateInputBean();
		requestParsingService0.validatePrivateEntityInputFields(createInputBean0, true);
	}

	@Test(timeout = 4000, expected = NullPointerException.class)
	public void test09() throws Exception {
		RequestParsingService requestParsingService0 = new RequestParsingService();
		requestParsingService0.validSupportedSearchTokens("Name");
	}

	@Test(timeout = 4000)
	public void test10() {
		RequestParsingService requestParsingService0 = new RequestParsingService();
		String string0 = requestParsingService0.getRefinedReqVal(null);
		assertNull(string0);
	}

	@Test(timeout = 4000)
	public void test11() {
		RequestParsingService requestParsingService0 = new RequestParsingService();
		String string0 =
				requestParsingService0.getRefinedReqVal(
						"javax.swing.text.StyledEditorKit$ForegroundAction@0000000002");
		assertNotNull(string0);
	}

	@Test(timeout = 4000)
	public void test12() {
		RequestParsingService requestParsingService0 = new RequestParsingService();
		String string0 = requestParsingService0.getRefinedReqVal((Object) null);
		assertNull(string0);
	}

	@Test(timeout = 4000)
	public void test13() {
		RequestParsingService requestParsingService0 = new RequestParsingService();
		FREntityMapping fREntityMapping0 = new FREntityMapping();
		String string0 = requestParsingService0.getRefinedReqVal(fREntityMapping0);
		assertNotNull(string0);
	}

	@Test(timeout = 4000)
	public void test14() {
		RequestParsingService requestParsingService0 = new RequestParsingService();
		JSONResponse jSONResponse0 =
				requestParsingService0.getErrorResponseForCatgorizerService(
						354, "_TJSBi{!A*cOi;DFVC", "_TJSBi{!A*cOi;DFVC", ";\"h!E=");
		assertEquals(";\"h!E=", jSONResponse0.getMessage());
		assertEquals(354, (int) jSONResponse0.getErrorCode());
	}

	@Test(timeout = 4000, expected = NullPointerException.class)
	public void test15() {
		RequestParsingService requestParsingService0 = new RequestParsingService();
		// Undeclared exception!
		requestParsingService0.getErrorResponseForCatgorizerService(
				1480, "V;%Yw?b|B*5>", " ", "V;%Yw?b|B*5>", true);
	}

	@Test(timeout = 4000, expected = NullPointerException.class)
	public void test16() {
		RequestParsingService requestParsingService0 = new RequestParsingService();
		// Undeclared exception!
		requestParsingService0.getErrorResponseForCatgorizerService(1480, "", " ", "", true);
	}

	@Test(timeout = 4000, expected = NullPointerException.class)
	public void test17() {
		RequestParsingService requestParsingService0 = new RequestParsingService();
		// Undeclared exception!
		requestParsingService0.getErrorResponseForCatgorizerService(
				322, "`m00p|mi[,kR${U", "`m00p|mi[,kR${U");
	}

	@Test(timeout = 4000, expected = NullPointerException.class)
	public void test18() {
		RequestParsingService requestParsingService0 = new RequestParsingService();
		// Undeclared exception!
		requestParsingService0.getErrorResponse((-4069), null);
	}

	@Test(timeout = 4000, expected = NullPointerException.class)
	public void test19() {
		RequestParsingService requestParsingService0 = new RequestParsingService();
		// Undeclared exception!
		requestParsingService0.getErrorResponse((-1532));
	}
}
