/*
 * This file was automatically generated by EvoSuite
 * Thu Jun 28 17:32:54 GMT 2018
 */

package com.firstrain.web.wrapper;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNull;

import com.firstrain.web.pojo.ChartData;
import java.util.List;
import org.junit.Test;


public class ChartDataWrapperESTest {

	@Test(timeout = 4000)
	public void test0() throws Exception {
		ChartDataWrapper chartDataWrapper0 = new ChartDataWrapper();
		chartDataWrapper0.setTitle("cTAe542~?");
		assertEquals("cTAe542~?", chartDataWrapper0.getTitle());
	}

	@Test(timeout = 4000)
	public void test1() throws Exception {
		ChartDataWrapper chartDataWrapper0 = new ChartDataWrapper();
		chartDataWrapper0.setNodes(null);
		assertNull(chartDataWrapper0.getTitle());
	}

	@Test(timeout = 4000)
	public void test2() throws Exception {
		ChartDataWrapper chartDataWrapper0 = new ChartDataWrapper();
		String string0 = chartDataWrapper0.getTitle();
		assertNull(string0);
	}

	@Test(timeout = 4000)
	public void test3() throws Exception {
		ChartDataWrapper chartDataWrapper0 = new ChartDataWrapper();
		List<ChartData> list0 = chartDataWrapper0.getNodes();
		assertNull(list0);
	}
}
