/*
 * This file was automatically generated by EvoSuite
 * Mon Jul 02 17:11:52 GMT 2018
 */

package com.firstrain.frapi.customapirepository.impl;

import org.junit.Test;


public class EntityBackTestRepositoryImplESTest {

	@Test(timeout = 4000, expected = NullPointerException.class)
	public void test0() throws Exception {
		EntityBackTestRepositoryImpl entityBackTestRepositoryImpl0 = new EntityBackTestRepositoryImpl();
		entityBackTestRepositoryImpl0.updateState("E]iHFq !sn*ct>j9d0", (-2480L));
	}
}
