/*
 * This file was automatically generated by EvoSuite
 * Thu Jun 28 17:08:07 GMT 2018
 */

package com.firstrain.frapi.domain;

import static org.junit.Assert.assertEquals;

import org.junit.Test;


public class CompanyTradingRangeESTest {

	@Test(timeout = 4000)
	public void test0() throws Exception {
		CompanyTradingRange companyTradingRange0 = new CompanyTradingRange();
		companyTradingRange0.setOpeningPrice(0.0);
		assertEquals(0.0, companyTradingRange0.getOpeningPrice(), 0.01);
		assertEquals((-1), companyTradingRange0.getDiffId());
		assertEquals(0.0, companyTradingRange0.getClosingPrice(), 0.01);
	}

	@Test(timeout = 4000)
	public void test1() throws Exception {
		CompanyTradingRange companyTradingRange0 = new CompanyTradingRange();
		assertEquals((-1), companyTradingRange0.getDiffId());

		companyTradingRange0.setDiffId(0);
		assertEquals(0, companyTradingRange0.getDiffId());
	}

	@Test(timeout = 4000)
	public void test2() throws Exception {
		CompanyTradingRange companyTradingRange0 = new CompanyTradingRange();
		companyTradingRange0.setClosingPrice(0.0);
		assertEquals(0.0, companyTradingRange0.getClosingPrice(), 0.01);
		assertEquals(0.0, companyTradingRange0.getOpeningPrice(), 0.01);
		assertEquals((-1), companyTradingRange0.getDiffId());
	}

	@Test(timeout = 4000)
	public void test3() throws Exception {
		CompanyTradingRange companyTradingRange0 = new CompanyTradingRange();
		String string0 = companyTradingRange0.getOpeningPriceStr();
		assertEquals("0.0", string0);
		assertEquals((-1), companyTradingRange0.getDiffId());
		assertEquals(0.0, companyTradingRange0.getClosingPrice(), 0.01);
	}

	@Test(timeout = 4000)
	public void test4() throws Exception {
		CompanyTradingRange companyTradingRange0 = new CompanyTradingRange();
		double double0 = companyTradingRange0.getOpeningPrice();
		assertEquals((-1), companyTradingRange0.getDiffId());
		assertEquals(0.0, companyTradingRange0.getClosingPrice(), 0.01);
		assertEquals(0.0, double0, 0.01);
	}

	@Test(timeout = 4000)
	public void test5() throws Exception {
		CompanyTradingRange companyTradingRange0 = new CompanyTradingRange();
		int int0 = companyTradingRange0.getDiffId();
		assertEquals((-1), int0);
		assertEquals(0.0, companyTradingRange0.getOpeningPrice(), 0.01);
		assertEquals(0.0, companyTradingRange0.getClosingPrice(), 0.01);
	}

	@Test(timeout = 4000)
	public void test6() throws Exception {
		CompanyTradingRange companyTradingRange0 = new CompanyTradingRange();
		String string0 = companyTradingRange0.getClosingPriceStr();
		assertEquals("0.0", string0);
		assertEquals(0.0, companyTradingRange0.getOpeningPrice(), 0.01);
		assertEquals((-1), companyTradingRange0.getDiffId());
	}

	@Test(timeout = 4000)
	public void test7() throws Exception {
		CompanyTradingRange companyTradingRange0 = new CompanyTradingRange();
		double double0 = companyTradingRange0.getClosingPrice();
		assertEquals(0.0, double0, 0.01);
		assertEquals((-1), companyTradingRange0.getDiffId());
		assertEquals(0.0, companyTradingRange0.getOpeningPrice(), 0.01);
	}
}
