/*
 * This file was automatically generated by EvoSuite
 * Thu Jun 28 17:07:00 GMT 2018
 */

package com.firstrain.frapi.domain;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertNull;
import static org.junit.Assert.assertTrue;

import com.firstrain.frapi.util.CompanyTeam;
import com.firstrain.frapi.util.ContentType;
import java.util.Date;
import java.util.List;
import org.evosuite.runtime.mock.java.util.MockDate;
import org.junit.Test;


public class DocumentESTest {

	@Test(timeout = 4000)
	public void test00() throws Exception {
		Document.DocQuote document_DocQuote0 = new Document.DocQuote();
		document_DocQuote0.setPerson(null);
		assertNull(document_DocQuote0.getPerson());
	}

	@Test(timeout = 4000)
	public void test01() throws Exception {
		Document.DocQuote document_DocQuote0 = new Document.DocQuote();
		String string0 = document_DocQuote0.getText();
		assertNull(string0);
	}

	@Test(timeout = 4000)
	public void test02() throws Exception {
		Document.DocQuote document_DocQuote0 = new Document.DocQuote();
		String string0 = document_DocQuote0.getPerson();
		assertNull(string0);
	}

	@Test(timeout = 4000)
	public void test03() throws Exception {
		Document.DocQuote document_DocQuote0 = new Document.DocQuote();
		document_DocQuote0.QUOTE_MARKER = "";
		document_DocQuote0.setText("7W*m64`13B&[<+");
		String string0 = document_DocQuote0.getHighlightedQuote();
		assertEquals("7W <b>*m64`13B</b> &[<+", string0);
	}

	@Test(timeout = 4000)
	public void test04() throws Exception {
		Document.DocQuote document_DocQuote0 = new Document.DocQuote();
		document_DocQuote0.QUOTE_MARKER = "";
		document_DocQuote0.setText("7F0=`o13B% $G[<~");
		String string0 = document_DocQuote0.getHighlightedQuote();
		assertEquals("7F0=`o13B%<b> $G[<~", string0);
	}

	@Test(timeout = 4000)
	public void test05() throws Exception {
		Document.DocQuote document_DocQuote0 = new Document.DocQuote("", "");
		document_DocQuote0.QUOTE_MARKER = "";
		document_DocQuote0.setText("10,=`o1ArB%\" $G[}>");
		document_DocQuote0.getHighlightedQuote();
		assertEquals("10,=`o1ArB%\" $G[}>", document_DocQuote0.getText());
	}

	@Test(timeout = 4000)
	public void test06() throws Exception {
		Document document0 = new Document();
		MetaShare metaShare0 = new MetaShare();
		document0.setVisibility(metaShare0);
		assertFalse(document0.isBookmarked());
	}

	@Test(timeout = 4000)
	public void test07() throws Exception {
		Document document0 = new Document();
		document0.setUrl(null);
		assertFalse(document0.isBookmarked());
	}

	@Test(timeout = 4000)
	public void test08() throws Exception {
		Document document0 = new Document();
		document0.setTitle("");
		assertFalse(document0.isBookmarked());
	}

	@Test(timeout = 4000)
	public void test09() throws Exception {
		Document document0 = new Document();
		document0.setSummary("l;l!'$E");
		assertFalse(document0.isBookmarked());
	}

	@Test(timeout = 4000)
	public void test10() throws Exception {
		Document document0 = new Document();
		document0.setSource(null);
		assertFalse(document0.isBookmarked());
	}

	@Test(timeout = 4000)
	public void test11() throws Exception {
		Document document0 = new Document();
		document0.setSlot(null);
		assertFalse(document0.isBookmarked());
	}

	@Test(timeout = 4000)
	public void test12() throws Exception {
		Document document0 = new Document();
		document0.setSimilarQuotesCount(null);
		assertFalse(document0.isBookmarked());
	}

	@Test(timeout = 4000)
	public void test13() throws Exception {
		Document document0 = new Document();
		document0.setSecFormType("");
		assertFalse(document0.isBookmarked());
	}

	@Test(timeout = 4000)
	public void test14() throws Exception {
		Document document0 = new Document();
		document0.setScore((-2014));
		assertEquals((-2014), document0.getScore());
	}

	@Test(timeout = 4000)
	public void test15() throws Exception {
		Document document0 = new Document();
		document0.setRoleEntities(null);
		assertFalse(document0.isBookmarked());
	}

	@Test(timeout = 4000)
	public void test16() throws Exception {
		Document document0 = new Document();
		document0.setRelatedTweets(null);
		assertFalse(document0.isBookmarked());
	}

	@Test(timeout = 4000)
	public void test17() throws Exception {
		Document document0 = new Document();
		document0.setRank(null);
		assertFalse(document0.isBookmarked());
	}

	@Test(timeout = 4000)
	public void test18() throws Exception {
		Document document0 = new Document();
		document0.setPrimaryEntity(null);
		assertFalse(document0.isBookmarked());
	}

	@Test(timeout = 4000)
	public void test19() throws Exception {
		Document document0 = new Document();
		document0.setPrimaryDunsMatchStr(null);
		assertFalse(document0.isBookmarked());
	}

	@Test(timeout = 4000)
	public void test20() throws Exception {
		Document document0 = new Document();
		document0.setPersonImageUrl("");
		assertFalse(document0.isBookmarked());
	}

	@Test(timeout = 4000)
	public void test21() throws Exception {
		Document document0 = new Document();
		document0.setPersonCatId(null);
		assertFalse(document0.isBookmarked());
	}

	@Test(timeout = 4000)
	public void test22() throws Exception {
		Document document0 = new Document();
		document0.setNgrams(null);
		assertFalse(document0.isBookmarked());
	}

	@Test(timeout = 4000)
	public void test23() throws Exception {
		Document document0 = new Document();
		document0.setMatchedTopics(null);
		assertFalse(document0.isBookmarked());
	}

	@Test(timeout = 4000)
	public void test24() throws Exception {
		Document document0 = new Document();
		com.firstrain.frapi.pojo.Entity entity0 = new com.firstrain.frapi.pojo.Entity();
		document0.setMatchedCriticalEvent(entity0);
		assertFalse(document0.isBookmarked());
	}

	@Test(timeout = 4000)
	public void test25() throws Exception {
		Document document0 = new Document();
		document0.setMatchedCompanies(null);
		assertFalse(document0.isBookmarked());
	}

	@Test(timeout = 4000)
	public void test26() throws Exception {
		Document document0 = new Document();
		document0.setLoginRequired(true);
		assertTrue(document0.isLoginRequired());
	}

	@Test(timeout = 4000)
	public void test27() throws Exception {
		Document document0 = new Document();
		document0.setItemId((-1L));
		assertEquals((-1L), document0.getItemId());
	}

	@Test(timeout = 4000)
	public void test28() throws Exception {
		Document document0 = new Document();
		document0.setInsertTime(null);
		assertFalse(document0.isBookmarked());
	}

	@Test(timeout = 4000)
	public void test29() throws Exception {
		Document document0 = new Document();
		document0.setImage(null);
		assertFalse(document0.isBookmarked());
	}

	@Test(timeout = 4000)
	public void test30() throws Exception {
		Document document0 = new Document();
		document0.setId("wDVQlvQWSR");
		assertFalse(document0.isBookmarked());
	}

	@Test(timeout = 4000)
	public void test31() throws Exception {
		Document document0 = new Document();
		Long long0 = 1572L;
		document0.setGroupId(long0);
		assertFalse(document0.isBookmarked());
	}

	@Test(timeout = 4000)
	public void test32() throws Exception {
		Document document0 = new Document();
		document0.setFavicon("Total:");
		assertFalse(document0.isBookmarked());
	}

	@Test(timeout = 4000)
	public void test33() throws Exception {
		Document document0 = new Document();
		document0.setDupCount(9642);
		assertEquals(9642, document0.getDupCount());
	}

	@Test(timeout = 4000)
	public void test34() throws Exception {
		Document document0 = new Document();
		document0.setDocQuote(null);
		assertFalse(document0.isBookmarked());
	}

	@Test(timeout = 4000)
	public void test35() throws Exception {
		Document document0 = new Document();
		MockDate mockDate0 = new MockDate();
		document0.setDate(mockDate0);
		assertFalse(document0.isBookmarked());
	}

	@Test(timeout = 4000)
	public void test36() throws Exception {
		Document document0 = new Document();
		CompanyTeam companyTeam0 = CompanyTeam.EXECUTIVE;
		document0.setCompanyTeam(companyTeam0);
		assertFalse(document0.isBookmarked());
	}

	@Test(timeout = 4000)
	public void test37() throws Exception {
		Document document0 = new Document();
		Boolean boolean0 = new Boolean("");
		document0.setCompanyPeople(boolean0);
		assertFalse(document0.isBookmarked());
	}

	@Test(timeout = 4000)
	public void test38() throws Exception {
		Document document0 = new Document();
		document0.setCompanyName("J~v>");
		assertFalse(document0.isBookmarked());
	}

	@Test(timeout = 4000)
	public void test39() throws Exception {
		Document document0 = new Document();
		document0.setCatEntries(null);
		assertFalse(document0.isBookmarked());
	}

	@Test(timeout = 4000)
	public void test40() throws Exception {
		Document document0 = new Document();
		assertFalse(document0.isBookmarked());

		document0.setBookmarked(true);
		assertTrue(document0.isBookmarked());
	}

	@Test(timeout = 4000)
	public void test41() throws Exception {
		Document document0 = new Document();
		document0.setAdditionalMatchQualifierStr("#B,BN#%_DR6>q-W#61");
		assertFalse(document0.isBookmarked());
	}

	@Test(timeout = 4000)
	public void test42() throws Exception {
		Document document0 = new Document();
		document0.isLoginRequired();
		assertFalse(document0.isBookmarked());
	}

	@Test(timeout = 4000)
	public void test43() throws Exception {
		Document document0 = new Document();
		boolean boolean0 = document0.isBookmarked();
		assertFalse(boolean0);
	}

	@Test(timeout = 4000)
	public void test44() throws Exception {
		Document document0 = new Document();
		document0.getVisibility();
		assertFalse(document0.isBookmarked());
	}

	@Test(timeout = 4000)
	public void test45() throws Exception {
		Document document0 = new Document();
		document0.getUrl();
		assertFalse(document0.isBookmarked());
	}

	@Test(timeout = 4000)
	public void test46() throws Exception {
		Document document0 = new Document();
		document0.getTitle();
		assertFalse(document0.isBookmarked());
	}

	@Test(timeout = 4000)
	public void test47() throws Exception {
		Document document0 = new Document();
		document0.getSummary();
		assertFalse(document0.isBookmarked());
	}

	@Test(timeout = 4000)
	public void test48() throws Exception {
		Document document0 = new Document();
		document0.getSource();
		assertFalse(document0.isBookmarked());
	}

	@Test(timeout = 4000)
	public void test49() throws Exception {
		Document document0 = new Document();
		document0.getSlot();
		assertFalse(document0.isBookmarked());
	}

	@Test(timeout = 4000)
	public void test50() throws Exception {
		Document document0 = new Document();
		document0.getSimilarQuotesCount();
		assertFalse(document0.isBookmarked());
	}

	@Test(timeout = 4000)
	public void test51() throws Exception {
		Document document0 = new Document();
		document0.getSecFormType();
		assertFalse(document0.isBookmarked());
	}

	@Test(timeout = 4000)
	public void test52() throws Exception {
		Document document0 = new Document();
		int int0 = document0.getScore();
		assertFalse(document0.isBookmarked());
		assertEquals(0, int0);
	}

	@Test(timeout = 4000)
	public void test53() throws Exception {
		Document document0 = new Document();
		document0.getRoleEntities();
		assertFalse(document0.isBookmarked());
	}

	@Test(timeout = 4000)
	public void test54() throws Exception {
		Document document0 = new Document();
		document0.getRelatedTweets();
		assertFalse(document0.isBookmarked());
	}

	@Test(timeout = 4000)
	public void test55() throws Exception {
		Document document0 = new Document();
		document0.getRank();
		assertFalse(document0.isBookmarked());
	}

	@Test(timeout = 4000)
	public void test56() throws Exception {
		Document document0 = new Document();
		document0.getPrimaryEntity();
		assertFalse(document0.isBookmarked());
	}

	@Test(timeout = 4000)
	public void test57() throws Exception {
		Document document0 = new Document();
		document0.getPrimaryDunsMatchStr();
		assertFalse(document0.isBookmarked());
	}

	@Test(timeout = 4000)
	public void test58() throws Exception {
		Document document0 = new Document();
		document0.getPersonImageUrl();
		assertFalse(document0.isBookmarked());
	}

	@Test(timeout = 4000)
	public void test59() throws Exception {
		Document document0 = new Document();
		document0.getPersonCatId();
		assertFalse(document0.isBookmarked());
	}

	@Test(timeout = 4000)
	public void test60() throws Exception {
		Document document0 = new Document();
		document0.getNgrams();
		assertFalse(document0.isBookmarked());
	}

	@Test(timeout = 4000)
	public void test61() throws Exception {
		Document document0 = new Document();
		document0.getMatchedTopics();
		assertFalse(document0.isBookmarked());
	}

	@Test(timeout = 4000)
	public void test62() throws Exception {
		Document document0 = new Document();
		document0.getMatchedCriticalEvent();
		assertFalse(document0.isBookmarked());
	}

	@Test(timeout = 4000)
	public void test63() throws Exception {
		Document document0 = new Document();
		document0.getMatchedCompanies();
		assertFalse(document0.isBookmarked());
	}

	@Test(timeout = 4000)
	public void test64() throws Exception {
		Document document0 = new Document();
		document0.getItemId();
		assertFalse(document0.isBookmarked());
	}

	@Test(timeout = 4000)
	public void test65() throws Exception {
		Document document0 = new Document();
		document0.getInsertTime();
		assertFalse(document0.isBookmarked());
	}

	@Test(timeout = 4000)
	public void test66() throws Exception {
		Document document0 = new Document();
		document0.getImage();
		assertFalse(document0.isBookmarked());
	}

	@Test(timeout = 4000)
	public void test67() throws Exception {
		Document document0 = new Document();
		document0.getId();
		assertFalse(document0.isBookmarked());
	}

	@Test(timeout = 4000)
	public void test68() throws Exception {
		Document document0 = new Document();
		document0.getGroupId();
		assertFalse(document0.isBookmarked());
	}

	@Test(timeout = 4000)
	public void test69() throws Exception {
		Document document0 = new Document();
		document0.getFavicon();
		assertFalse(document0.isBookmarked());
	}

	@Test(timeout = 4000)
	public void test70() throws Exception {
		Document document0 = new Document();
		int int0 = document0.getDupCount();
		assertEquals(0, int0);
		assertFalse(document0.isBookmarked());
	}

	@Test(timeout = 4000)
	public void test71() throws Exception {
		Document document0 = new Document();
		document0.getDocQuote();
		assertFalse(document0.isBookmarked());
	}

	@Test(timeout = 4000)
	public void test72() throws Exception {
		Document document0 = new Document();
		document0.getDate();
		assertFalse(document0.isBookmarked());
	}

	@Test(timeout = 4000)
	public void test73() throws Exception {
		Document document0 = new Document();
		ContentType contentType0 = document0.getContentType();
		document0.setContentType(contentType0);
		assertFalse(document0.isBookmarked());
	}

	@Test(timeout = 4000)
	public void test74() throws Exception {
		Document document0 = new Document();
		document0.getCompanyTeam();
		assertFalse(document0.isBookmarked());
	}

	@Test(timeout = 4000)
	public void test75() throws Exception {
		Document document0 = new Document();
		document0.getCompanyPeople();
		assertFalse(document0.isBookmarked());
	}

	@Test(timeout = 4000)
	public void test76() throws Exception {
		Document document0 = new Document();
		document0.getCompanyName();
		assertFalse(document0.isBookmarked());
	}

	@Test(timeout = 4000)
	public void test77() throws Exception {
		Document document0 = new Document();
		document0.getCatEntries();
		assertFalse(document0.isBookmarked());
	}

	@Test(timeout = 4000)
	public void test78() throws Exception {
		Document document0 = new Document();
		document0.getAdditionalMatchQualifierStr();
		assertFalse(document0.isBookmarked());
	}
}
