/*
 * This file was automatically generated by EvoSuite
 * Thu Jun 28 16:59:27 GMT 2018
 */

package com.firstrain.frapi.domain;

import static org.junit.Assert.assertArrayEquals;
import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNull;

import java.util.Set;
import org.junit.Test;


public class IndustryBriefDomainESTest {

	@Test(timeout = 4000)
	public void test0() throws Exception {
		IndustryBriefDomain industryBriefDomain0 = new IndustryBriefDomain();
		industryBriefDomain0.setTopicToken("");
		assertEquals("", industryBriefDomain0.getTopicToken());
	}

	@Test(timeout = 4000)
	public void test1() throws Exception {
		IndustryBriefDomain industryBriefDomain0 = new IndustryBriefDomain();
		int[] intArray0 = new int[4];
		industryBriefDomain0.setTopicIdsArray(intArray0);
		assertNull(industryBriefDomain0.getTopicToken());
	}

	@Test(timeout = 4000)
	public void test2() throws Exception {
		IndustryBriefDomain industryBriefDomain0 = new IndustryBriefDomain();
		industryBriefDomain0.setTopicId(0);
		assertEquals(0, industryBriefDomain0.getTopicId());
	}

	@Test(timeout = 4000)
	public void test3() throws Exception {
		IndustryBriefDomain industryBriefDomain0 = new IndustryBriefDomain();
		int[] intArray0 = new int[4];
		industryBriefDomain0.setCompanyIdsArray(intArray0);
		assertArrayEquals(new int[]{0, 0, 0, 0}, intArray0);
	}

	@Test(timeout = 4000)
	public void test4() throws Exception {
		IndustryBriefDomain industryBriefDomain0 = new IndustryBriefDomain();
		industryBriefDomain0.setCategoryIdsSet(null);
		assertNull(industryBriefDomain0.getTopicToken());
	}

	@Test(timeout = 4000)
	public void test5() throws Exception {
		IndustryBriefDomain industryBriefDomain0 = new IndustryBriefDomain();
		String string0 = industryBriefDomain0.getTopicToken();
		assertNull(string0);
	}

	@Test(timeout = 4000)
	public void test6() throws Exception {
		IndustryBriefDomain industryBriefDomain0 = new IndustryBriefDomain();
		int[] intArray0 = industryBriefDomain0.getTopicIdsArray();
		assertNull(intArray0);
	}

	@Test(timeout = 4000)
	public void test7() throws Exception {
		IndustryBriefDomain industryBriefDomain0 = new IndustryBriefDomain();
		int int0 = industryBriefDomain0.getTopicId();
		assertEquals(0, int0);
	}

	@Test(timeout = 4000)
	public void test8() throws Exception {
		IndustryBriefDomain industryBriefDomain0 = new IndustryBriefDomain();
		int[] intArray0 = industryBriefDomain0.getCompanyIdsArray();
		assertNull(intArray0);
	}

	@Test(timeout = 4000)
	public void test9() throws Exception {
		IndustryBriefDomain industryBriefDomain0 = new IndustryBriefDomain();
		Set<String> set0 = industryBriefDomain0.getCategoryIdsSet();
		assertNull(set0);
	}
}
