package com.firstrain.frapi.domain;

import static org.junit.Assert.assertArrayEquals;

import com.firstrain.frapi.domain.ManagementChange.MgmtChangeType;
import org.junit.Rule;
import org.junit.Test;
import org.junit.rules.ExpectedException;
import org.junit.rules.Timeout;

public class ManagementChangeDiffblueTest {

  @Rule public final ExpectedException thrown = ExpectedException.none();
  @Rule public final Timeout globalTimeout = new Timeout(10_000);

  /* testedClasses: ManagementChange */
  // Test generated by Diffblue Deeptest.

  @Test
  public void valuesOutput3() {

    // Act
    final MgmtChangeType[] retval = MgmtChangeType.values();

    // Assert
    assertArrayEquals(
        new MgmtChangeType[] {
          MgmtChangeType.HIRE, MgmtChangeType.DEPARTURE, MgmtChangeType.INTERNALMOVE
        },
        retval);
  }
}
