/*
 * This file was automatically generated by EvoSuite
 * Thu Jun 28 16:58:16 GMT 2018
 */

package com.firstrain.frapi.domain;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertNull;
import static org.junit.Assert.assertTrue;

import org.junit.Test;


public class MonitorEmailESTest {

	@Test(timeout = 4000)
	public void test00() throws Exception {
		MonitorEmail monitorEmail0 = new MonitorEmail();
		monitorEmail0.setTimeStamp("");
		assertEquals("", monitorEmail0.getTimeStamp());
	}

	@Test(timeout = 4000)
	public void test01() throws Exception {
		MonitorEmail monitorEmail0 = new MonitorEmail();
		monitorEmail0.setSubject("! 5=*");
		assertNull(monitorEmail0.getEmailId());
	}

	@Test(timeout = 4000)
	public void test02() throws Exception {
		MonitorEmail monitorEmail0 = new MonitorEmail();
		monitorEmail0.hashCode();
	}

	@Test(timeout = 4000)
	public void test03() throws Exception {
		MonitorEmail monitorEmail0 = new MonitorEmail();
		String string0 = monitorEmail0.getTimeStamp();
		assertNull(string0);
	}

	@Test(timeout = 4000)
	public void test04() throws Exception {
		MonitorEmail monitorEmail0 = new MonitorEmail();
		String string0 = monitorEmail0.getSubject();
		assertNull(string0);
	}

	@Test(timeout = 4000)
	public void test05() throws Exception {
		MonitorEmail monitorEmail0 = new MonitorEmail();
		String string0 = monitorEmail0.getEmailId();
		assertNull(string0);
	}

	@Test(timeout = 4000)
	public void test06() throws Exception {
		MonitorEmail monitorEmail0 = new MonitorEmail();
		monitorEmail0.setEmailId("']EQs");
		MonitorEmail monitorEmail1 = new MonitorEmail();
		boolean boolean0 = monitorEmail0.equals(monitorEmail1);
		assertFalse(boolean0);
	}

	@Test(timeout = 4000)
	public void test07() throws Exception {
		MonitorEmail monitorEmail0 = new MonitorEmail();
		monitorEmail0.setEmailId("']EQs");
		MonitorEmail monitorEmail1 = new MonitorEmail();
		boolean boolean0 = monitorEmail1.equals(monitorEmail0);
		assertFalse(boolean0);
	}

	@Test(timeout = 4000)
	public void test08() throws Exception {
		MonitorEmail monitorEmail0 = new MonitorEmail();
		MonitorEmail monitorEmail1 = new MonitorEmail();
		boolean boolean0 = monitorEmail0.equals(monitorEmail1);
		assertTrue(boolean0);
	}

	@Test(timeout = 4000)
	public void test09() throws Exception {
		MonitorEmail monitorEmail0 = new MonitorEmail();
		boolean boolean0 = monitorEmail0.equals(null);
		assertFalse(boolean0);
	}

	@Test(timeout = 4000)
	public void test10() throws Exception {
		MonitorEmail monitorEmail0 = new MonitorEmail();
		boolean boolean0 = monitorEmail0.equals(monitorEmail0);
		assertTrue(boolean0);
	}

	@Test(timeout = 4000)
	public void test11() throws Exception {
		MonitorEmail monitorEmail0 = new MonitorEmail();
		Object object0 = new Object();
		boolean boolean0 = monitorEmail0.equals(object0);
		assertFalse(boolean0);
	}
}
