package com.firstrain.frapi.domain;

import static org.junit.Assert.assertEquals;

import com.diffblue.deeptestutils.Reflector;
import org.junit.Rule;
import org.junit.Test;
import org.junit.rules.ExpectedException;
import org.junit.rules.Timeout;

public class MonitorInfoDiffblueTest {

  @Rule public final ExpectedException thrown = ExpectedException.none();
  @Rule public final Timeout globalTimeout = new Timeout(10_000);

  /* testedClasses: MonitorInfo */
  // Test generated by Diffblue Deeptest.

  @Test
  public void hashCodeOutputPositive() throws Exception {

    // Arrange
    final MonitorInfo objectUnderTest =
        (MonitorInfo) Reflector.getInstance("com.firstrain.frapi.domain.MonitorInfo");
    objectUnderTest.setOwnedByType(null);
    objectUnderTest.setFavorite(false);
    objectUnderTest.setOwnedBy(null);
    objectUnderTest.setMonitorName(null);
    objectUnderTest.setMailBadge(null);
    objectUnderTest.setMailAvailable(null);
    objectUnderTest.setMonitorId("");
    objectUnderTest.setHasNew(null);
    objectUnderTest.setFavoriteUserItemId(null);
    objectUnderTest.setTweetAvailable(null);
    objectUnderTest.setManagementTurnoverAvailable(null);
    objectUnderTest.setMonitorAdmin(false);
    objectUnderTest.setItemCount(null);
    objectUnderTest.setEventAvailable(null);

    // Act
    final int retval = objectUnderTest.hashCode();

    // Assert
    assertEquals(31, retval);
  }
}
