/*
 * This file was automatically generated by EvoSuite
 * Thu Jun 28 17:09:46 GMT 2018
 */

package com.firstrain.frapi.domain;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertNull;

import org.junit.Test;


public class SecEventMetaESTest {

	@Test(timeout = 4000)
	public void test00() throws Exception {
		SecEventMeta secEventMeta0 = new SecEventMeta();
		secEventMeta0.setSecId(null);
		assertNull(secEventMeta0.getSecId());
	}

	@Test(timeout = 4000)
	public void test01() throws Exception {
		SecEventMeta secEventMeta0 = new SecEventMeta();
		String string0 = "t\\W8=i>8f\\u";
		secEventMeta0.setOriginalTitle(string0);
		secEventMeta0.getSeceTitleWithoutHtml("TYPE_EIGHT_K_EVENT_ITEM_5_06");
		assertEquals("Change in Shell Company Status", secEventMeta0.getOriginalTitle());
	}

	@Test(timeout = 4000)
	public void test02() throws Exception {
		SecEventMeta secEventMeta0 = createSecEventMeta(); 
		String string0 = secEventMeta0.getSecTitleWithoutHtml();
		assertEquals("}4Z6<;UL!kp**`<0", string0);
	}

	@Test(timeout = 4000)
	public void test03() throws Exception {
		SecEventMeta secEventMeta0 = new SecEventMeta();
		secEventMeta0.setOriginalTitle("TYPE_TEN_Q_EVENT");
		String string0 = secEventMeta0.getSeceTitleWithoutHtml("TYPE_TEN_Q_EVENT");
		assertEquals("TYPE_TEN_Q_EVENT", string0);
	}

	@Test(timeout = 4000)
	public void test04() throws Exception {
		SecEventMeta secEventMeta0 = new SecEventMeta();
		secEventMeta0.setOriginalTitle("@}g/Z");
		String string0 = secEventMeta0.getSeceTitleWithoutHtml("TYPE_TEN_K_EVENT");
		assertEquals("@}g/Z", string0);
	}

	@Test(timeout = 4000)
	public void test05() throws Exception {
		SecEventMeta secEventMeta0 = new SecEventMeta();
		secEventMeta0.setOriginalTitle(":pwmv=<K'=?U");
		String string0 = secEventMeta0.getSecTitleWithoutHtml();
		assertEquals("", string0);
	}

	@Test(timeout = 4000)
	public void test06() throws Exception {
		SecEventMeta secEventMeta0 = new SecEventMeta();
		secEventMeta0.setOriginalTitle(".g\"@c4l,s{uDZ8u=dQ");
		String string0 = secEventMeta0.getSecTitleWithoutHtml();
		assertEquals("", string0);
	}

	@Test(timeout = 4000)
	public void test07() throws Exception {
		SecEventMeta secEventMeta0 = new SecEventMeta();
		String string0 = "t\\W8=i>8f\\u";
		secEventMeta0.setOriginalTitle(string0);
		secEventMeta0.getSeceTitle("TYPE_EIGHT_K_EVENT_ITEM_5_06");
		assertEquals("Change in Shell Company Status", secEventMeta0.getOriginalTitle());
	}

	@Test(timeout = 4000, expected = ArrayIndexOutOfBoundsException.class)
	public void test08() throws Exception {
		SecEventMeta secEventMeta0 = createSecEventMeta(); 
		// Undeclared exception!
		secEventMeta0.getSecTitle();
	}
 
	private SecEventMeta createSecEventMeta() { 
		SecEventMeta secEventMeta0 = new SecEventMeta(); 
		secEventMeta0.setSecFormType("10-Q/A"); 
		secEventMeta0.setOriginalTitle("}4Z6<;UL!kp**`<0"); 
		return secEventMeta0; 
	} 

	@Test(timeout = 4000, expected = ArrayIndexOutOfBoundsException.class)
	public void test09() throws Exception {
		SecEventMeta secEventMeta0 = new SecEventMeta();
		secEventMeta0.setOriginalTitle("TYPE_TEN_Q_EVENT");
		// Undeclared exception!
		secEventMeta0.getSeceTitle("TYPE_TEN_Q_EVENT");
	}

	@Test(timeout = 4000, expected = NullPointerException.class)
	public void test10() throws Exception {
		SecEventMeta secEventMeta0 = new SecEventMeta();
		secEventMeta0.setOriginalTitle("TYPE_TEN_K_EVENT");
		// Undeclared exception!
		secEventMeta0.getSeceTitle("TYPE_TEN_K_EVENT");
	}

	@Test(timeout = 4000)
	public void test11() throws Exception {
		SecEventMeta secEventMeta0 = new SecEventMeta();
		secEventMeta0.setOriginalTitle(".g\"@c4l,s{uDZ8u=dQ");
		String string0 = secEventMeta0.getSecTitle();
		assertEquals("", string0);
	}

	@Test(timeout = 4000)
	public void test12() throws Exception {
		SecEventMeta secEventMeta0 = new SecEventMeta();
		secEventMeta0.setOriginalTitle(":pwmv=<K'=?U");
		String string0 = secEventMeta0.getSecTitle();
		assertEquals("", string0);
	}

	@Test(timeout = 4000)
	public void test13() throws Exception {
		SecEventMeta secEventMeta0 = new SecEventMeta();
		String string0 = secEventMeta0.getSecId();
		assertNull(string0);
	}

	@Test(timeout = 4000)
	public void test14() throws Exception {
		SecEventMeta secEventMeta0 = new SecEventMeta();
		String string0 = secEventMeta0.getSecFormType();
		assertNull(string0);
	}

	@Test(timeout = 4000)
	public void test15() throws Exception {
		SecEventMeta secEventMeta0 = new SecEventMeta();
		String string0 = secEventMeta0.getSeceTitleWithoutHtml("TYPE_DELAYED_SEC_FILING");
		assertNotNull(string0);
		assertEquals("Delayed SEC Filings : null", string0);
	}

	@Test(timeout = 4000)
	public void test16() throws Exception {
		SecEventMeta secEventMeta0 = new SecEventMeta();
		String string0 = secEventMeta0.getSeceTitle("TYPE_DELAYED_SEC_FILING");
		assertEquals("<span></span> <br/>SEC Delay: null", string0);
		assertNotNull(string0);
	}

	@Test(timeout = 4000)
	public void test17() throws Exception {
		SecEventMeta secEventMeta0 = new SecEventMeta();
		String string0 = secEventMeta0.getOriginalTitle();
		assertNull(string0);
	}
}
