/*
 * This file was automatically generated by EvoSuite
 * Thu Jun 28 17:00:19 GMT 2018
 */

package com.firstrain.frapi.domain;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNull;

import org.junit.Test;


public class StockPriceMetaESTest {

	@Test(timeout = 4000)
	public void test00() throws Exception {
		StockPriceMeta stockPriceMeta0 = new StockPriceMeta();
		stockPriceMeta0.setTradingVolume("e^;47CFX1@>0Vl/C");
		assertNull(stockPriceMeta0.getAvg50Day());
	}

	@Test(timeout = 4000)
	public void test01() throws Exception {
		StockPriceMeta stockPriceMeta0 = new StockPriceMeta();
		stockPriceMeta0.setPreviousClosingPrice(
				"Stock Price: Stock Closing Price Contra to Industry Composite by >5%");
		assertNull(stockPriceMeta0.getClosingPrice());
	}

	@Test(timeout = 4000)
	public void test02() throws Exception {
		StockPriceMeta stockPriceMeta0 = new StockPriceMeta();
		stockPriceMeta0
				.setOpeningPrice("Stock Price: Stock Closing Price Contra to Industry Composite by >5%");
		assertNull(stockPriceMeta0.getTradingVolume());
	}

	@Test(timeout = 4000)
	public void test03() throws Exception {
		StockPriceMeta stockPriceMeta0 = new StockPriceMeta();
		stockPriceMeta0.setMinPrice("p%sEY$AibmD\"jhX8n");
		assertNull(stockPriceMeta0.getAvg50Day());
	}

	@Test(timeout = 4000)
	public void test04() throws Exception {
		StockPriceMeta stockPriceMeta0 = new StockPriceMeta();
		stockPriceMeta0.setMaxPrice("zxR7~");
		assertEquals("zxR7~", stockPriceMeta0.getMaxPrice());
	}

	@Test(timeout = 4000)
	public void test05() throws Exception {
		StockPriceMeta stockPriceMeta0 = new StockPriceMeta();
		stockPriceMeta0.setAvg200Day("p%sEY$AibmD\"jhX8n");
		assertNull(stockPriceMeta0.getPercentChange());
	}

	@Test(timeout = 4000)
	public void test06() throws Exception {
		StockPriceMeta stockPriceMeta0 = new StockPriceMeta();
		String string0 = stockPriceMeta0.getTradingVolume();
		assertNull(string0);
	}

	@Test(timeout = 4000)
	public void test07() throws Exception {
		StockPriceMeta stockPriceMeta0 = new StockPriceMeta();
		stockPriceMeta0.setClosingPrice("0");
		stockPriceMeta0.setPercentChange("-");
		stockPriceMeta0.getSPTitleWithoutHtml(300);
		assertEquals("0.00", stockPriceMeta0.getClosingPrice());
	}

	@Test(timeout = 4000)
	public void test08() throws Exception {
		StockPriceMeta stockPriceMeta0 = createStockPriceMeta(); 
		stockPriceMeta0.getSPTitleWithoutHtml(300);
		assertEquals("50.00", stockPriceMeta0.getClosingPrice());
	}

	@Test(timeout = 4000)
	public void test09() throws Exception {
		StockPriceMeta stockPriceMeta0 = new StockPriceMeta();
		stockPriceMeta0.setClosingPrice("MMP");
		stockPriceMeta0.setPercentChange("MMP");
		String string0 = stockPriceMeta0.getSPTitleWithoutHtml(300);
		assertEquals("Stock price CLOSED UP +MMP% at $MMP", string0);
	}

	@Test(timeout = 4000)
	public void test10() throws Exception {
		StockPriceMeta stockPriceMeta0 = createStockPriceMetaWithAvg100DayClosingPrice(); 
		stockPriceMeta0.getSPTitleWithoutHtml(302);
		assertEquals("3.00", stockPriceMeta0.getClosingPrice());
	}

	@Test(timeout = 4000)
	public void test11() throws Exception {
		StockPriceMeta stockPriceMeta0 = createStockPriceMetaWithClosingPriceAvg52Week(); 
		String string0 = stockPriceMeta0.getSPTitleWithoutHtml(304);
		assertEquals(
				"Stock closing price ($#EMMP) DROPPED BELOW 52-week Moving Average ($Stock Price: Stock Closing Price Contra to Industry Composite by >5%)",
				string0);
	}

	@Test(timeout = 4000)
	public void test12() throws Exception {
		StockPriceMeta stockPriceMeta0 = new StockPriceMeta();
		stockPriceMeta0.setClosingPrice("K,X>:zVCD2mr$[S!");
		stockPriceMeta0.setAvg50Day("50-day Moving Average");
		String string0 = stockPriceMeta0.getSPTitleWithoutHtml(301);
		assertEquals(
				"Stock closing price ($K,X>:zVCD2mr$[S!) DROPPED BELOW 50-day Moving Average ($50.00)",
				string0);
	}

	@Test(timeout = 4000, expected = NullPointerException.class)
	public void test13() throws Exception {
		StockPriceMeta stockPriceMeta0 = new StockPriceMeta();
		stockPriceMeta0.setClosingPrice("#EMMP");
		// Undeclared exception!
		stockPriceMeta0.getSPTitleWithoutHtml(303);
	}

	@Test(timeout = 4000)
	public void test14() throws Exception {
		StockPriceMeta stockPriceMeta0 = new StockPriceMeta();
		stockPriceMeta0.setClosingPrice("K,X>:zVCD2mr$[S!");
		String string0 = stockPriceMeta0.getSPTitleWithoutHtml((-1815));
		assertEquals("Stock Price: Stock Closing Price Contra to Industry Composite by >5%", string0);
	}

	@Test(timeout = 4000)
	public void test15() throws Exception {
		StockPriceMeta stockPriceMeta0 = new StockPriceMeta();
		stockPriceMeta0.setClosingPrice("Z");
		stockPriceMeta0.setPercentChange("-");
		String string0 = stockPriceMeta0.getSPTitle(300, true);
		assertEquals(
				"Stock price <span style='text-transform:uppercase;font-size:90%'><span style='color:#e82d2d'>CLOSED DOWN -%</span></span> at $Z",
				string0);
	}

	@Test(timeout = 4000)
	public void test16() throws Exception {
		StockPriceMeta stockPriceMeta0 = createStockPriceMeta(); 
		stockPriceMeta0.getSPTitle(300, false);
		assertEquals("50.00", stockPriceMeta0.getClosingPrice());
	}
 
	private StockPriceMeta createStockPriceMeta() { 
		StockPriceMeta stockPriceMeta0 = new StockPriceMeta(); 
		stockPriceMeta0.setClosingPrice("50-day Moving Average"); 
		stockPriceMeta0.setPercentChange("50-day Moving Average"); 
		return stockPriceMeta0; 
	} 

	@Test(timeout = 4000)
	public void test17() throws Exception {
		StockPriceMeta stockPriceMeta0 = createStockPriceMetaWithAvg100DayClosingPrice(); 
		stockPriceMeta0.getSPTitle(302, true);
		assertEquals("3.00", stockPriceMeta0.getClosingPrice());
	}
 
	private StockPriceMeta createStockPriceMetaWithAvg100DayClosingPrice() { 
		StockPriceMeta stockPriceMeta0 = new StockPriceMeta(); 
		stockPriceMeta0 
				.setAvg100Day("Stock Price: Stock Closing Price Contra to Industry Composite by >5%"); 
		stockPriceMeta0.setClosingPrice("3G-J%8IpeG'JZj"); 
		return stockPriceMeta0; 
	} 

	@Test(timeout = 4000)
	public void test18() throws Exception {
		StockPriceMeta stockPriceMeta0 = createStockPriceMetaWithClosingPriceAvg52Week(); 
		String string0 = stockPriceMeta0.getSPTitle(304, true);
		assertEquals(
				"Stock closing price <span style='text-transform:uppercase;font-size:90%'>($#EMMP) <span style='color:#e82d2d'>DROPPED BELOW</span> 52-week Moving Average</span> ($Stock Price: Stock Closing Price Contra to Industry Composite by >5%)",
				string0);
	}
 
	private StockPriceMeta createStockPriceMetaWithClosingPriceAvg52Week() { 
		StockPriceMeta stockPriceMeta0 = new StockPriceMeta(); 
		stockPriceMeta0.setClosingPrice("#EMMP"); 
		stockPriceMeta0 
				.setAvg52Week("Stock Price: Stock Closing Price Contra to Industry Composite by >5%"); 
		return stockPriceMeta0; 
	} 

	@Test(timeout = 4000)
	public void test19() throws Exception {
		StockPriceMeta stockPriceMeta0 = new StockPriceMeta();
		stockPriceMeta0.setClosingPrice("MMP");
		stockPriceMeta0.setAvg50Day("1N]^&>JbD3G6*Vi~X0}");
		String string0 = stockPriceMeta0.getSPTitle(301, true);
		assertEquals(
				"Stock closing price <span style='text-transform:uppercase;font-size:90%'>($MMP) <span style='color:#e82d2d'>DROPPED BELOW</span> 50-day Moving Average</span> ($1.00)",
				string0);
	}

	@Test(timeout = 4000, expected = NullPointerException.class)
	public void test20() throws Exception {
		StockPriceMeta stockPriceMeta0 = new StockPriceMeta();
		stockPriceMeta0.setClosingPrice("#EMMP");
		// Undeclared exception!
		stockPriceMeta0.getSPTitle(303, true);
	}

	@Test(timeout = 4000)
	public void test21() throws Exception {
		StockPriceMeta stockPriceMeta0 = new StockPriceMeta();
		stockPriceMeta0.setClosingPrice("K,X>:zVCD2mr$[S!");
		String string0 = stockPriceMeta0.getSPTitle((-1708), true);
		assertEquals("Stock Price: Stock Closing Price Contra to Industry Composite by >5%", string0);
	}

	@Test(timeout = 4000, expected = NullPointerException.class)
	public void test22() throws Exception {
		StockPriceMeta stockPriceMeta0 = new StockPriceMeta();
		// Undeclared exception!
		stockPriceMeta0.getPriceChange();
	}

	@Test(timeout = 4000)
	public void test23() throws Exception {
		StockPriceMeta stockPriceMeta0 = new StockPriceMeta();
		String string0 = stockPriceMeta0.getPreviousClosingPrice();
		assertNull(string0);
	}

	@Test(timeout = 4000)
	public void test24() throws Exception {
		StockPriceMeta stockPriceMeta0 = new StockPriceMeta();
		String string0 = stockPriceMeta0.getPercentChange();
		assertNull(string0);
	}

	@Test(timeout = 4000)
	public void test25() throws Exception {
		StockPriceMeta stockPriceMeta0 = new StockPriceMeta();
		String string0 = stockPriceMeta0.getOpeningPrice();
		assertNull(string0);
	}

	@Test(timeout = 4000)
	public void test26() throws Exception {
		StockPriceMeta stockPriceMeta0 = new StockPriceMeta();
		String string0 = stockPriceMeta0.getMinPrice();
		assertNull(string0);
	}

	@Test(timeout = 4000)
	public void test27() throws Exception {
		StockPriceMeta stockPriceMeta0 = new StockPriceMeta();
		String string0 = stockPriceMeta0.getMaxPrice();
		assertNull(string0);
	}

	@Test(timeout = 4000)
	public void test28() throws Exception {
		StockPriceMeta stockPriceMeta0 = new StockPriceMeta();
		String string0 = stockPriceMeta0.getClosingPrice();
		assertNull(string0);
	}

	@Test(timeout = 4000)
	public void test29() throws Exception {
		StockPriceMeta stockPriceMeta0 = new StockPriceMeta();
		String string0 = stockPriceMeta0.getAvg52Week();
		assertNull(string0);
	}

	@Test(timeout = 4000)
	public void test30() throws Exception {
		StockPriceMeta stockPriceMeta0 = new StockPriceMeta();
		String string0 = stockPriceMeta0.getAvg50Day();
		assertNull(string0);
	}

	@Test(timeout = 4000)
	public void test31() throws Exception {
		StockPriceMeta stockPriceMeta0 = new StockPriceMeta();
		String string0 = stockPriceMeta0.getAvg200Day();
		assertNull(string0);
	}

	@Test(timeout = 4000)
	public void test32() throws Exception {
		StockPriceMeta stockPriceMeta0 = new StockPriceMeta();
		String string0 = stockPriceMeta0.getAvg100Day();
		assertNull(string0);
	}
}
