/*
 * This file was automatically generated by EvoSuite
 * Thu Jun 28 17:00:43 GMT 2018
 */

package com.firstrain.frapi.domain;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertNull;

import com.firstrain.frapi.pojo.wrapper.EntityListJsonObject;
import com.firstrain.frapi.util.DefaultEnums;
import org.junit.Test;


public class UserESTest {

	@Test(timeout = 4000)
	public void test00() throws Exception {
		User user0 = new User();
		DefaultEnums.UserType defaultEnums_UserType0 = DefaultEnums.UserType.ABU;
		user0.setUserType(defaultEnums_UserType0);
		assertNull(user0.getOwnedByType());
	}

	@Test(timeout = 4000)
	public void test01() throws Exception {
		User user0 = new User();
		EntityListJsonObject entityListJsonObject0 = new EntityListJsonObject();
		user0.setUserTriggers(entityListJsonObject0);
		assertEquals(DefaultEnums.MembershipType.DEFAULT, user0.getMembershipType());
	}

	@Test(timeout = 4000)
	public void test02() throws Exception {
		User user0 = new User();
		user0.setUserName("");
		assertNull(user0.getStatus());
	}

	@Test(timeout = 4000)
	public void test03() throws Exception {
		User user0 = new User();
		user0.setUserId("XE`]f");
		assertNull(user0.getUserType());
	}

	@Test(timeout = 4000)
	public void test04() throws Exception {
		User user0 = new User();
		user0.setUserCompany("");
		assertNull(user0.getTimeZone());
	}

	@Test(timeout = 4000)
	public void test05() throws Exception {
		User user0 = new User();
		user0.setTimeZone("2~zzu'{/GZVoPOM");
		assertNull(user0.getStatus());
	}

	@Test(timeout = 4000)
	public void test06() throws Exception {
		User user0 = new User();
		user0.setTemplateId(0L);
		assertEquals(0L, user0.getFrMonitorId());
	}

	@Test(timeout = 4000)
	public void test07() throws Exception {
		User user0 = new User();
		DefaultEnums.UserValidationStatus defaultEnums_UserValidationStatus0 = DefaultEnums.UserValidationStatus.GROUP_VALIDATION_FAILURE;
		user0.setStatus(defaultEnums_UserValidationStatus0);
		assertEquals(0L, user0.getOwnedBy());
	}

	@Test(timeout = 4000)
	public void test08() throws Exception {
		User user0 = new User();
		user0.setOwnedByType(null);
		assertEquals(0L, user0.getTemplateId());
	}

	@Test(timeout = 4000)
	public void test09() throws Exception {
		User user0 = new User();
		user0.setOwnedBy((-1L));
		assertEquals((-1L), user0.getOwnedBy());
	}

	@Test(timeout = 4000)
	public void test10() throws Exception {
		User user0 = new User();
		DefaultEnums.Origin defaultEnums_Origin0 = DefaultEnums.Origin.START_HERE_KNOWN;
		user0.setOrigin(defaultEnums_Origin0);
		assertEquals(0L, user0.getTemplateId());
	}

	@Test(timeout = 4000)
	public void test11() throws Exception {
		User user0 = new User();
		user0.setMonitorOrderType("INACTIVE");
		assertNull(user0.getOwnedByType());
	}

	@Test(timeout = 4000)
	public void test12() throws Exception {
		User user0 = new User();
		DefaultEnums.MembershipType defaultEnums_MembershipType0 = DefaultEnums.MembershipType.DEFAULT;
		user0.setMembershipType(defaultEnums_MembershipType0);
		assertNull(user0.getUserCompany());
	}

	@Test(timeout = 4000)
	public void test13() throws Exception {
		User user0 = new User();
		user0.setLastName("]%pzGB");
		assertEquals(DefaultEnums.MembershipType.DEFAULT, user0.getMembershipType());
	}

	@Test(timeout = 4000)
	public void test14() throws Exception {
		User user0 = new User();
		user0.setFrMonitorId(1L);
		assertEquals(1L, user0.getFrMonitorId());
	}

	@Test(timeout = 4000)
	public void test15() throws Exception {
		User user0 = new User();
		user0.setFormat(0);
		assertEquals(0, user0.getFormat());
	}

	@Test(timeout = 4000)
	public void test16() throws Exception {
		User user0 = new User();
		user0.setFlags("");
		assertNull(user0.getLastName());
	}

	@Test(timeout = 4000)
	public void test17() throws Exception {
		User user0 = new User();
		user0.setFirstName("");
		assertNull(user0.getLastName());
	}

	@Test(timeout = 4000)
	public void test18() throws Exception {
		User user0 = new User();
		user0.setEmail("com.firstrain.frapi.domain.User");
		assertNull(user0.getMonitorOrderType());
	}

	@Test(timeout = 4000)
	public void test19() throws Exception {
		User user0 = new User();
		user0.setDomain("e,8bUYz");
		assertNull(user0.getUserName());
	}

	@Test(timeout = 4000)
	public void test20() throws Exception {
		User user0 = new User();
		user0.setDnbUserId("g");
		assertFalse(user0.isContextPage());
	}

	@Test(timeout = 4000)
	public void test21() throws Exception {
		User user0 = new User();
		user0.setContextPage(false);
		assertFalse(user0.isContextPage());
	}

	@Test(timeout = 4000)
	public void test22() throws Exception {
		User user0 = new User();
		user0.setCode(null);
		assertNull(user0.getUserId());
	}

	@Test(timeout = 4000)
	public void test23() throws Exception {
		User user0 = new User();
		boolean boolean0 = user0.isContextPage();
		assertFalse(boolean0);
	}

	@Test(timeout = 4000)
	public void test24() throws Exception {
		User user0 = new User();
		user0.getUserType();
	}

	@Test(timeout = 4000)
	public void test25() throws Exception {
		User user0 = new User();
		EntityListJsonObject entityListJsonObject0 = user0.getUserTriggers();
		assertNull(entityListJsonObject0);
	}

	@Test(timeout = 4000)
	public void test26() throws Exception {
		User user0 = new User();
		String string0 = user0.getUserName();
		assertNull(string0);
	}

	@Test(timeout = 4000)
	public void test27() throws Exception {
		User user0 = new User();
		String string0 = user0.getUserId();
		assertNull(string0);
	}

	@Test(timeout = 4000)
	public void test28() throws Exception {
		User user0 = new User();
		String string0 = user0.getUserCompany();
		assertNull(string0);
	}

	@Test(timeout = 4000)
	public void test29() throws Exception {
		User user0 = new User();
		String string0 = user0.getTimeZone();
		assertNull(string0);
	}

	@Test(timeout = 4000)
	public void test30() throws Exception {
		User user0 = new User();
		long long0 = user0.getTemplateId();
		assertEquals(0L, long0);
	}

	@Test(timeout = 4000)
	public void test31() throws Exception {
		User user0 = new User();
		user0.getStatus();
	}

	@Test(timeout = 4000)
	public void test32() throws Exception {
		User user0 = new User();
		String string0 = user0.getOwnedByType();
		assertNull(string0);
	}

	@Test(timeout = 4000)
	public void test33() throws Exception {
		User user0 = new User();
		long long0 = user0.getOwnedBy();
		assertEquals(0L, long0);
	}

	@Test(timeout = 4000)
	public void test34() throws Exception {
		User user0 = new User();
		user0.getOrigin();
	}

	@Test(timeout = 4000)
	public void test35() throws Exception {
		User user0 = new User();
		String string0 = user0.getMonitorOrderType();
		assertNull(string0);
	}

	@Test(timeout = 4000)
	public void test36() throws Exception {
		User user0 = new User();
		DefaultEnums.MembershipType defaultEnums_MembershipType0 = user0.getMembershipType();
		assertEquals(DefaultEnums.MembershipType.DEFAULT, defaultEnums_MembershipType0);
	}

	@Test(timeout = 4000)
	public void test37() throws Exception {
		User user0 = new User();
		String string0 = user0.getLastName();
		assertNull(string0);
	}

	@Test(timeout = 4000)
	public void test38() throws Exception {
		User user0 = new User();
		long long0 = user0.getFrMonitorId();
		assertEquals(0L, long0);
	}

	@Test(timeout = 4000)
	public void test39() throws Exception {
		User user0 = new User();
		int int0 = user0.getFormat();
		assertEquals(0, int0);
	}

	@Test(timeout = 4000)
	public void test40() throws Exception {
		User user0 = new User();
		String string0 = user0.getFlags();
		assertNull(string0);
	}

	@Test(timeout = 4000)
	public void test41() throws Exception {
		User user0 = new User();
		String string0 = user0.getFirstName();
		assertNull(string0);
	}

	@Test(timeout = 4000)
	public void test42() throws Exception {
		User user0 = new User();
		String string0 = user0.getEmail();
		assertNull(string0);
	}

	@Test(timeout = 4000)
	public void test43() throws Exception {
		User user0 = new User();
		String string0 = user0.getDomain();
		assertNull(string0);
	}

	@Test(timeout = 4000)
	public void test44() throws Exception {
		User user0 = new User();
		String string0 = user0.getDnbUserId();
		assertNull(string0);
	}

	@Test(timeout = 4000)
	public void test45() throws Exception {
		User user0 = new User();
		String string0 = user0.getCode();
		assertNull(string0);
	}
}
