/*
 * This file was automatically generated by EvoSuite
 * Thu Jun 28 17:01:33 GMT 2018
 */

package com.firstrain.frapi.domain;

import org.junit.Test;


public class WebVolumeEventMetaESTest {

	@Test(timeout = 4000)
	public void test0() throws Exception {
		WebVolumeEventMeta webVolumeEventMeta0 = new WebVolumeEventMeta();
	}
}
