/*
 * This file was automatically generated by EvoSuite
 * Thu Jun 28 17:43:54 GMT 2018
 */

package com.firstrain.web.pojo;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNull;

import java.util.List;
import java.util.Map;
import org.junit.Test;


public class DefinitionESTest {

	@Test(timeout = 4000)
	public void test0() throws Exception {
		Definition definition0 = new Definition();
		definition0.setPhrases(null);
		assertNull(definition0.getMatchRule());
	}

	@Test(timeout = 4000)
	public void test1() throws Exception {
		Definition definition0 = new Definition();
		definition0.setMatchRule("");
		assertEquals("", definition0.getMatchRule());
	}

	@Test(timeout = 4000)
	public void test2() throws Exception {
		Definition definition0 = new Definition();
		definition0.setInstructions(null);
		assertNull(definition0.getMatchRule());
	}

	@Test(timeout = 4000)
	public void test3() throws Exception {
		Definition definition0 = new Definition();
		Map<String, List<String>> map0 = definition0.getPhrases();
		assertNull(map0);
	}

	@Test(timeout = 4000)
	public void test4() throws Exception {
		Definition definition0 = new Definition();
		String string0 = definition0.getMatchRule();
		assertNull(string0);
	}

	@Test(timeout = 4000)
	public void test5() throws Exception {
		Definition definition0 = new Definition();
		Map<String, InstructionDefinition> map0 = definition0.getInstructions();
		assertNull(map0);
	}
}
