/*
 * This file was automatically generated by EvoSuite
 * Thu Jun 28 17:36:39 GMT 2018
 */

package com.firstrain.web.pojo;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNull;

import com.firstrain.frapi.util.DefaultEnums;
import java.util.List;
import org.junit.Test;


public class EventESTest {

	@Test(timeout = 4000)
	public void test00() throws Exception {
		Event event0 = new Event();
		event0.setTitle("Rr>CtP?TAxX%r1fpV");
		assertNull(event0.getId());
	}

	@Test(timeout = 4000)
	public void test01() throws Exception {
		Event event0 = new Event();
		event0.setTimeStamp("r\"R0c");
		assertNull(event0.getNewTitle());
	}

	@Test(timeout = 4000)
	public void test02() throws Exception {
		Event event0 = new Event();
		Source source0 = new Source();
		event0.setSource(source0);
		assertNull(source0.getSearchToken());
	}

	@Test(timeout = 4000)
	public void test03() throws Exception {
		Event event0 = new Event();
		event0.setSnippet(null);
		assertNull(event0.getSnippet());
	}

	@Test(timeout = 4000)
	public void test04() throws Exception {
		Event event0 = new Event();
		event0.setPersonFullName("");
		assertNull(event0.getTimeStamp());
	}

	@Test(timeout = 4000)
	public void test05() throws Exception {
		Event event0 = new Event();
		event0.setOldTitle(null);
		assertNull(event0.getContentType());
	}

	@Test(timeout = 4000)
	public void test06() throws Exception {
		Event event0 = new Event();
		event0.setOldRegion("4he/V");
		assertNull(event0.getSnippet());
	}

	@Test(timeout = 4000)
	public void test07() throws Exception {
		Event event0 = new Event();
		event0.setOldGroup(null);
		assertNull(event0.getPersonFullName());
	}

	@Test(timeout = 4000)
	public void test08() throws Exception {
		Event event0 = new Event();
		event0.setOldCompany(null);
		assertNull(event0.getEventDate());
	}

	@Test(timeout = 4000)
	public void test09() throws Exception {
		Event event0 = new Event();
		event0.setNewTitle("YioL");
		assertNull(event0.getId());
	}

	@Test(timeout = 4000)
	public void test10() throws Exception {
		Event event0 = new Event();
		event0.setNewRegion("n=+KKY.Q?HY*d");
		assertNull(event0.getTimeStamp());
	}

	@Test(timeout = 4000)
	public void test11() throws Exception {
		Event event0 = new Event();
		event0.setNewGroup("6NtiD!.(Xv<)1-");
		assertNull(event0.getContentType());
	}

	@Test(timeout = 4000)
	public void test12() throws Exception {
		Event event0 = new Event();
		event0.setNewCompany(null);
		assertNull(event0.getTimeStamp());
	}

	@Test(timeout = 4000)
	public void test13() throws Exception {
		Event event0 = new Event();
		event0.setLink("");
		assertNull(event0.getNewRegion());
	}

	@Test(timeout = 4000)
	public void test14() throws Exception {
		Event event0 = new Event();
		event0.setId("n=+KKY.Q?HY*d");
		assertEquals("n=+KKY.Q?HY*d", event0.getId());
	}

	@Test(timeout = 4000)
	public void test15() throws Exception {
		Event event0 = new Event();
		DefaultEnums.EventInformationEnum defaultEnums_EventInformationEnum0 = DefaultEnums.EventInformationEnum.PRICE_DOWN;
		event0.setEventType(defaultEnums_EventInformationEnum0);
		assertNull(event0.getEventDate());
	}

	@Test(timeout = 4000)
	public void test16() throws Exception {
		Event event0 = new Event();
		event0.setEventDate("");
		assertNull(event0.getContentType());
	}

	@Test(timeout = 4000)
	public void test17() throws Exception {
		Event event0 = new Event();
		event0.setEntity(null);
		assertNull(event0.getEventDate());
	}

	@Test(timeout = 4000)
	public void test18() throws Exception {
		Event event0 = new Event();
		event0.setContentType(null);
		assertNull(event0.getTimeStamp());
	}

	@Test(timeout = 4000)
	public void test19() throws Exception {
		Event event0 = new Event();
		String string0 = event0.getTitle();
		assertNull(string0);
	}

	@Test(timeout = 4000)
	public void test20() throws Exception {
		Event event0 = new Event();
		String string0 = event0.getTimeStamp();
		assertNull(string0);
	}

	@Test(timeout = 4000)
	public void test21() throws Exception {
		Event event0 = new Event();
		Source source0 = event0.getSource();
		assertNull(source0);
	}

	@Test(timeout = 4000)
	public void test22() throws Exception {
		Event event0 = new Event();
		String string0 = event0.getSnippet();
		assertNull(string0);
	}

	@Test(timeout = 4000)
	public void test23() throws Exception {
		Event event0 = new Event();
		String string0 = event0.getPersonFullName();
		assertNull(string0);
	}

	@Test(timeout = 4000)
	public void test24() throws Exception {
		Event event0 = new Event();
		String string0 = event0.getOldTitle();
		assertNull(string0);
	}

	@Test(timeout = 4000)
	public void test25() throws Exception {
		Event event0 = new Event();
		String string0 = event0.getOldRegion();
		assertNull(string0);
	}

	@Test(timeout = 4000)
	public void test26() throws Exception {
		Event event0 = new Event();
		String string0 = event0.getOldGroup();
		assertNull(string0);
	}

	@Test(timeout = 4000)
	public void test27() throws Exception {
		Event event0 = new Event();
		EntityStandard entityStandard0 = event0.getOldCompany();
		assertNull(entityStandard0);
	}

	@Test(timeout = 4000)
	public void test28() throws Exception {
		Event event0 = new Event();
		String string0 = event0.getNewTitle();
		assertNull(string0);
	}

	@Test(timeout = 4000)
	public void test29() throws Exception {
		Event event0 = new Event();
		String string0 = event0.getNewRegion();
		assertNull(string0);
	}

	@Test(timeout = 4000)
	public void test30() throws Exception {
		Event event0 = new Event();
		String string0 = event0.getNewGroup();
		assertNull(string0);
	}

	@Test(timeout = 4000)
	public void test31() throws Exception {
		Event event0 = new Event();
		EntityStandard entityStandard0 = event0.getNewCompany();
		assertNull(entityStandard0);
	}

	@Test(timeout = 4000)
	public void test32() throws Exception {
		Event event0 = new Event();
		String string0 = event0.getLink();
		assertNull(string0);
	}

	@Test(timeout = 4000)
	public void test33() throws Exception {
		Event event0 = new Event();
		String string0 = event0.getId();
		assertNull(string0);
	}

	@Test(timeout = 4000)
	public void test34() throws Exception {
		Event event0 = new Event();
		event0.getEventType();
	}

	@Test(timeout = 4000)
	public void test35() throws Exception {
		Event event0 = new Event();
		String string0 = event0.getEventDate();
		assertNull(string0);
	}

	@Test(timeout = 4000)
	public void test36() throws Exception {
		Event event0 = new Event();
		List<EntityStandard> list0 = event0.getEntity();
		assertNull(list0);
	}

	@Test(timeout = 4000)
	public void test37() throws Exception {
		Event event0 = new Event();
		String string0 = event0.getContentType();
		assertNull(string0);
	}
}
